### ISSUE TITLE
Fix library compatibility

### ISSUE THREAD

**Issue by R3dst0ne** [logisim-evolution/logisim-evolution#1000]
Libraries that worked in release 3.5.0 currently don't work with the latest development version.

Steps to reproduce:
(In current development build)
Click on `Project` > `Load Library` > `JAR Library...`.
Select a JAR Library. (E.g. [MIDIkeyboard](https://github.com/mrmcsoftware/MIDIkeyboard))

**Comment by MarcinOrlowski** [comment]
CC: @sderrien

**Comment by BFH-ktt1** [comment]
@R3dst0ne : Could you do some more testing to see if my latest PR fixes the problem?

**Comment by R3dst0ne** [comment]
It seems to work.
