### ISSUE TITLE
74161/74163 cascading issues

### ISSUE THREAD

**Issue by oetzy** [logisim-evolution/logisim-evolution#1092]
The datasheet for the 74161/74163 specifies that TC/RC0 is high only when EnT is also high. In Logisim it stays high as EnT gets low. When set to 1111 via the input lines, TC/RC0 is only set if EnT was already high from previous clock cycle.

**Comment by BFH-ktt1** [comment]
Should be fixed in my latest PR, closing. Please reopen if the problem persists.
