### ISSUE TITLE
IllegalArgumentException while starting LSe

### ISSUE THREAD

**Issue by MarcinOrlowski** [logisim-evolution/logisim-evolution#1101]
### Discussed in https://github.com/logisim-evolution/logisim-evolution/discussions/1095

<div type='discussions-op-text'>

<sup>Originally posted by **marpol1992** September 14, 2021</sup>
I have a problem starting the application version 3.6.0. I have jdk-16.0.2 and jre1.8.0_301 installed, but it returns an error at startup "Failed to launch JVM" </div>

**Comment by MarcinOrlowski** [comment]
For a record, this affects only users with system locale set to Polish.

**Comment by BFH-ktt1** [comment]
I think that we should maybe plan the roll-out of v3.7.0 soon, and not to try to back port it in v3.6.0, What do you think?

**Comment by MarcinOrlowski** [comment]
I am fine with 3.7.0 release. So let's set release date, freeze date and then let's go with [procedure](https://github.com/logisim-evolution/logisim-evolution/discussions/1004).

* #1004

**Comment by MarcinOrlowski** [comment]
Closing ticket as fixed.
