### ISSUE TITLE
Auto-updater unable to fetch data resulting in a white window in Arch Linux

### ISSUE THREAD

**Issue by MonAaraj** [logisim-evolution/logisim-evolution#1117]
After installing and running the logisim-evolution-bin AUR package, I see this window flash:
![An image of logisim's auto-updater window](https://user-images.githubusercontent.com/46468162/134453813-7043528c-ed86-4177-a74c-30ec6027c171.png)
Then, this as well:
![An image of the logisim splash screen window](https://user-images.githubusercontent.com/46468162/134453934-5d93716d-9c87-4596-b287-c63c3c6e3b31.png)
and finally, just a window with a white screen shows and stays up, though my mouse pointer does show the little pressing thing and the + sign when i right click on some places, but that's about it. Luckily, there's some useful-looking output when I run it from the terminal:
```
[main] ERROR com.cburch.logisim.gui.start.Startup - Although an Internet connection should be available, the system couldn't retrieve the data requested by the auto-updater.
If the error persist, please contact the software maintainer
-- AUTO-UPDATE ABORTED --
```

**Comment by MarcinOrlowski** [comment]
Please install recent version of LSe which is v3.6.0: https://github.com/logisim-evolution/logisim-evolution#download
