### ISSUE TITLE
The 74163 parallel load is broken

### ISSUE THREAD

**Issue by Noobie2014** [logisim-evolution/logisim-evolution#1142]
I last sent an erroneous issue and am sorry for the mistake but this time i think i found one. I am sending this circuit for you to debug the issue. I have a 74161 and a 74163 wired the same and I can get the 74161 to load a parallel input but for the life of me I can't get the 74163 to load one. The chips are identical all except the clear input for one is asynchronous and the other synchronous.

[soloCntr.zip](https://github.com/logisim-evolution/logisim-evolution/files/7241275/soloCntr.zip)

**Comment by BFH-ktt1** [comment]
Thanks for your Issue!

**Comment by MarcinOrlowski** [comment]
> I last sent an erroneous issue and am sorry for the mistake but this time i think i found one. 

No worries @Noobie2014. This is nothing unusual. Thanks for spending the time to file the ticket (regardless of the final outcome).

**Comment by MarcinOrlowski** [comment]
Closing as fixed (please grab nightly and try). Please reopen if needed.
