### ISSUE TITLE
Is there a 74173 model anywhere?

### ISSUE THREAD

**Issue by TheByteAttic** [logisim-evolution/logisim-evolution#1208]
Looking for a 74173 model that works with LogiSim Evolution (older logisim libraries containing that IC don't seem to work). Is there anything already available anywhere?

**Comment by TheByteAttic** [comment]
Thanks Marcin!

**Comment by MarcinOrlowski** [comment]
I am closing this one as this is more like discussions thread than issue ticked. Please reopen if you think it's premature, you want to contribute or so.
