### ISSUE TITLE
MUX in existing files just lost its enable line

### ISSUE THREAD

**Issue by davidhutchens** [logisim-evolution/logisim-evolution#1210]
I have a MUX in an existing project that lost its enable line setting. It had an enable, but that is now set to NO on load. Now the project doesn't run. I just fetched and built from the current develop branch. I haven't yet checked if this is a consistent problem. I'll look at it more tomorrow.

This project worked a day or two ago.

**Comment by BFH-ktt1** [comment]
@davidhutchens : This could well be a backward compatibility issue introduced by my PR #1203. Could you look with which version the ```.circ``` was generated, I can than look into the details.

**Comment by BFH-ktt1** [comment]
P.s. this would than also hold for the demultiplexor

**Comment by BFH-ktt1** [comment]
@davidhutchens , closing this issue as solved in #1212, please reopen if you find other "bugs" related to #1203.
