### ISSUE TITLE
74161 counter model doesn't work

### ISSUE THREAD

**Issue by TheByteAttic** [logisim-evolution/logisim-evolution#1223]
Cascading the built-in 74161 models to create larger counters, precisely according to the circuit indicated in TI's datasheet, leads to wrong counting behavior when there is a ripple carry going across ICs. Sometimes the RCO output won't go HIGH when it should do so, and the other way around.

More specifically, RCO should go _asynchronously_ HIGH whenever all four output bits and EnT are HIGH, regardless of the clock; and RCO should go _asynchronously_ LOW whenever any of the output bits or EnT goes LOW (see page 3 of the datasheet linked below). But this doesn't happen. Instead, the behavior of RCO seems to be gated by the clock. This seems to be leading to all kinds of problems when these models are cascaded. In addition, sometimes the output bits (Q1 to Q4) don't clear when their counting wraps around in a cascade structure.

Unfortunately I cannot access the circuit being used, as this is a built-in module. The same problem seems to affect the 74163 model, which has the additional problem that the load input doesn't seem to work. For reference, the cascading circuit I am using, and which doesn't work when the counting goes across ICs, is the one on page 11 of this datasheet:

https://www.ti.com/lit/ds/symlink/sn74hc161.pdf

Any chance this can be corrected soon?

**Comment by BFH-ktt1** [comment]
@TheByteAttic : Could you please send a .zip file with the circuit that is not working, such that I can try to reproduce?
