### ISSUE TITLE
I/O pins in 74245

### ISSUE THREAD

**Issue by TheByteAttic** [logisim-evolution/logisim-evolution#1224]
I've made my own model of the 74245 bus transceivers. But there is no way to specify that certain pins can be inputs OR outputs, depending on the value of another pin (in this case, DIR). The tool requires that pins either be inputs always, or outputs always. This prevents models of transceivers. Is there a solution to this?

**Comment by MarcinOrlowski** [comment]
We shall update the docs and add "Current limitations" list mentioning these few most asked features missing

**Comment by MarcinOrlowski** [comment]
Added #1225

* #1225

**Comment by MarcinOrlowski** [comment]
We plan to have simulation engine improved to lift this limitation but this is not yet done, co I am closing this ticket as `wont-fix` as this is currently the only option.
