### ISSUE TITLE
Logisim-evolution fails to download design on to an FPGA board if more than two are connected at the same time

### ISSUE THREAD

**Issue by maehne** [logisim-evolution/logisim-evolution#123]
If more than one FPGA boards are connected to a PC (in my case two GECKO4-EDUCATION), the download on the board fails with:
```
Error (213043): More than one programming cable found in available hardware list -- use --list option to display available hardware list and specify correct programming cable
```
It would be more user-friendly, if the user would be simply prompted to select which of the attached programming cables he would like to use.

**Comment by BFH-ktt1** [comment]
Agreed, the FPGA-commander was never tested with more than one board attached, and hence this situation never apeared before. To be able to make sure that a user-selection works in all situations we have to dig into the details how to detect/handle multiple boards/programmer cables in case of Xilinx and Altera. I'll put it on the to-do list. For the time being please connect only one board/programmer cable to your machine.
