### ISSUE TITLE
Incorrect buffer behaviour when `Output Value` is not set to `0/1`

### ISSUE THREAD

**Issue by MinekPo1** [logisim-evolution/logisim-evolution#1249]
When a buffer has `Output Value` set to either `floating/1` or `0/floating`, instead of floating, the gate returns error.

ls-e:
![image](https://user-images.githubusercontent.com/68391527/137938812-cb126884-8a85-465b-a3f5-a9b5870d9918.png)

original ls:
![image](https://user-images.githubusercontent.com/68391527/137938868-a838ae11-40f6-4d15-a3e2-82cda7c1e274.png)

Both are set to `floating/1`.

**Comment by MinekPo1** [comment]
I have confirmed this still happens in 3.7.1

**Comment by maehne** [comment]
Thanks for reporting @MinekPo1! I can confirm this issue. It also does not help adding a pull resistor:

![grafik](https://user-images.githubusercontent.com/1174243/139962136-1c35b7f0-495a-446f-bab2-c93b877ff2ba.png)

**Comment by jendo42** [comment]
Seems like NOT gate is working correctly.

**Comment by BFH-ktt1** [comment]
Should be fixed in nightly build. If the problem persists, please reopen
