### ISSUE TITLE
unable to display the minimized expression in combinational analysis

### ISSUE THREAD

**Issue by jeritt** [logisim-evolution/logisim-evolution#1260]
v 3.7 windows

For any expression, I can see and work with defining inputs and outputs, truth table, and expressions fine, but it seems to be problematic when displaying the k-map / minimized logic tab.

Consider this very simple example of AND logic:

![image](https://user-images.githubusercontent.com/49690937/138355368-664deb11-8e0e-44ac-945e-c44b38f694b1.png)

**Comment by BFH-ktt1** [comment]
Closing as #1266 is merged. Please reopen if the problem persists,
