### ISSUE TITLE
Mac .dmg fails on recent macOS releases

### ISSUE THREAD

**Issue by davidhutchens** [logisim-evolution/logisim-evolution#1267]
This issue is related to the discussion in #1201 and the report by @aalcaineo and @ahanek.

I have reproduced the issue on macOS 10.15.7. It seems that Apple has changed something about the way Gatekeeper is working. I have a potential solution that I am investigating.

@ahanek: You stated that the .jar file was not working also. I do not see a problem with it. Did you download the .jar from here or did you try to open the .jar that is included in the application inside the .dmg? Also, the .jar requires at least Java 16. Please check your installed java version. You may need to upgrade. Let me know what you find.

**Comment by BFH-ktt1** [comment]
@ahanek : The minimized tab problem is related to #1260 and is fixed with #1266.

**Comment by BFH-ktt1** [comment]
Closing as #1271 and #1266 are merged. Please reopen if the problem persists.

**Comment by davidhutchens** [comment]
@aalcaineo and @ahanek : Could you please download the dmg from our [nightly builds](https://github.com/logisim-evolution/logisim-evolution/actions/workflows/nightly.yml) and check to see if you can open it on macOS 11? It should fix the tab problem also. Let us know if it works.

**Comment by aalcaineo** [comment]
It loads! thank you!

I opened it on macOS 12 indeed ;)
