### ISSUE TITLE
When using the merge feature, circuit appearance pin position resets to default

### ISSUE THREAD

**Issue by mb200002** [logisim-evolution/logisim-evolution#1272]
I observed In logisim-evolution V3.7.1 that the pin position of circuit blocks resets to the default position while merging circuit files.

**Comment by maehne** [comment]
This behaviour was observed by several students during last week's lab when they merged their individual work together to the group's solution. All were using the latest stable Logisim-evolution version 3.7.1.

**Comment by BFH-ktt1** [comment]
Closing as fixed in #1281. Please reopen if the problem persists
