### ISSUE TITLE
Create and edit the appearance of a sub-circuit in v3.8.0-dev still doesn't work as expected

### ISSUE THREAD

**Issue by chenzhuoyu** [logisim-evolution/logisim-evolution#1289]
As mentioned in #1280, editing newly created sub-circuits in v3.7.1+ doesn't work anymore.

I have tested the latest develop branch, the pin-movement bug disappear, but the main issue persists: I still cannot edit subcircuit's appearance, and the duplicated-origin still exists when I open in v3.7.0.

I cannot reopen the issue #1280 that wasn't closed by myself, so I created this new issue.

**Comment by BFH-ktt1** [comment]
Dear @chenzhuoyu : V3.7.0 still contains the bugs, hence it is normal that the duplicate origin exists when opening in V3.7.0. This cannot be fixed, as V3.7.0 is the problem. When you have still the problem with the nightly build than let me know.
