### ISSUE TITLE
use of bitextender makes synthesis stop working

### ISSUE THREAD

**Issue by primechaser** [logisim-evolution/logisim-evolution#1309]
Hi Team,

while playing with Altera's DE0 board, I realized that using the bitextender makes the synthesis stop working. I understand using the splitter is a workaround, but I thought, you might want to know.

environment:
OS: windows 10
JRE version 17.0.1
logisim-evolution 3.7.2 (jar version

[bit extender.zip](https://github.com/logisim-evolution/logisim-evolution/files/7625409/bit.extender.zip)
)
quartus II 18.1

**Comment by BFH-ktt1** [comment]
Fixed in develop, closing, please reopen if the problem persists
