### ISSUE TITLE
XNOR logic gate wrong output (3 inputs)

### ISSUE THREAD

**Issue by gbzinsheikk** [logisim-evolution/logisim-evolution#1321]
Recently I've observed an error when trying to use the XNOR logic gate in logisim-evolution. With three entries, it gives an output error in the case that all three entries are 1(high logic level), it gives an output of one, when it should be zero, accordingly with the truth table of this gate.

**Comment by esseivan** [comment]
There's an option "Multiple-Input Behavior" when selecting the xor / xnor gate. To have a real xor you want to select the 2nd option in this parameter.
I believe this 2nd option should be the default one.

**Comment by BFH-ktt1** [comment]
@gbzinsheikk : Basically a XOR/XNOR gate with more than 2 Inputs do not exists, as there are than two definitions for the behavior, either 1) react only when 1 input is active (the default behavior) , or 2) react when an odd/even number of inputs is active (parity generation).
I always suggest to do a cascading of XOR/XNOR gates when more than 2 inputs are required, or use alternatively the Odd/Even Parity blocks if the other functionality is required.
Closing this issue as the behavior currently in logisim-evolution is correct.
