### ISSUE TITLE
components

### ISSUE THREAD

**Issue by KimchiTheDone** [logisim-evolution/logisim-evolution#1329]
I would like to build this PC myself and I would need it for it. A list of the components. I wanted to ask if there is a list of the required components.

**Comment by maehne** [comment]
I am sorry, but you'll have to be much more specific with your enhancement request. What would you like to design? What components are you missing? Logisim-evolution is already capable to model/simulate an entire computer at gate level and also on a more abstract transaction-based level (using the System on Chip Library). With a web search, you can find various project examples.

Therefore, I'll close this issue for the moment. Feel free to Re-open it with a more specific request or better use our discussion forums.
