### ISSUE TITLE
Add Some Common CPU Built (Or All CPU And MCU)

### ISSUE THREAD

**Issue by cheznewa** [logisim-evolution/logisim-evolution#1330]
Hello , Is Possible To Add CPUs Built (Not As Circuit) Like i386 ARM ... ?
Docs ::::: https://github.com/larsbrinkhoff/awesome-cpus

**Comment by BFH-ktt1** [comment]
The SOC library provides all the means, so PR's are welcome!

**Comment by maehne** [comment]
The SoC library already provides instruction set simulators for RISC V and Nios II. If you would like to see other instruction set architectures to be supported, please be more specific and, ideally, open a pull request. Implementing and maintaining support for new processor architectures requires effort and therefore should be driven by a concrete demand.

For the moment, I consider your question answered. Feel free to reopen it to make your request more precise.
