### ISSUE TITLE
Output register value is incorrect after 4 bits, this is a bug

### ISSUE THREAD

**Issue by RepolhoIguinorante** [logisim-evolution/logisim-evolution#1364]
The register has a bug in its output, when connected by a wire to a BCD for Hexadecimal display, when the number exceeds 4 bits, it starts to generate some random numbers...

**Comment by MarcinOrlowski** [comment]
Please include project file (as ZIP) demonstrating the issue. What version of LSe it is?

**Comment by RepolhoIguinorante** [comment]
Ok

**Comment by RepolhoIguinorante** [comment]
I already posted the example project...

**Comment by RepolhoIguinorante** [comment]
> Please include project file (as ZIP) demonstrating the issue. What version of LSe it is? 

My version of LogiSim Evolution is 3.7.2 is the latest

**Comment by RepolhoIguinorante** [comment]
![Captura de Tela (2)](https://user-images.githubusercontent.com/87026115/149431598-2baca7ea-a73a-461a-8dda-732ae1f4eda0.png)

**Comment by RepolhoIguinorante** [comment]
You got it?

In the register we have a number, but in the wire we have another...

This bug gives BCD confusion. The Hexadecimal Display for example, shows a totally wrong number of what should be shown...

**Comment by RepolhoIguinorante** [comment]
Please fix this...

**Comment by BFH-ktt1** [comment]
I'm unsure what you mean. From your picture the value stored in the register is 0xaa, which correspond to 10101010b shown on the wire, which in respect corresponds to -86 when using 2's Complement interpretation. Hence all shown in the picture is correct. Please be more specific on the error you think is present.

**Comment by RepolhoIguinorante** [comment]
Thanks for the reply...But, (0×aa) or (aa) is equal to 170 and not to -86...

**Comment by BFH-ktt1** [comment]
10101010b equals 170 in "unsigned" binary interpretation, 10101010b equals -42 in sign and magnitude "signed" interpretation, and 10101010b equals to -86 in two's complement "signed" interpretation. Hence it depends how you interpret this set of bits. Therefore I do not see a bug here, as the numbers are correct.

**Comment by BFH-ktt1** [comment]
![Screenshot from 2022-01-14 06-57-26](https://user-images.githubusercontent.com/13875618/149459125-4e2aee1d-b54b-4bbf-a173-ec623721b2ab.png)
You can change the interpretation in the settings under ```Secon radix when wire poked```, which is default on ```Signed Decimal```(2's complement). When you change it to ```Unsigned Decimal``` the 170 will appear. Closing issue as I do not see a bug here.
