### ISSUE TITLE
zooming in is always zooming to top left 

### ISSUE THREAD

**Issue by xExtrude** [logisim-evolution/logisim-evolution#1368]
hey, just updated to 3.7.2 from 3.5.1 and noticed that if i press ctrl and the zoom it always zoom to the top left instead of zooming to the point of the cursor.
didnt happend for me in 3.5.1.

**Comment by dbh201** [comment]
I already have this fixed locally, should I do a pull request?

**Comment by maehne** [comment]
Yes, please against branch `develop`.

**Comment by BFH-ktt1** [comment]
Can this issue be closed as PR #1370 got merged?
