### ISSUE TITLE
enhancement request: auto-save?

### ISSUE THREAD

**Issue by aidan-gibson** [logisim-evolution/logisim-evolution#1384]
Would adding an auto-save feature be trivial?

**Comment by maehne** [comment]
I like your proposal. The implementation effort should be reasonable. The autosave delay should parameterisable in de program settings. Default could be, e.g., 10 min.

**Comment by prlaba** [comment]
I second this one!

I lost a bunch of circuit changes recently when my system crashed (not Logisim's fault that my system crashed).

**Comment by basil-conto** [comment]
Was this enhancement request addressed by #1965?

**Comment by maehne** [comment]
Yes, this enhancement has been implemented by PR #1965.
