### ISSUE TITLE
7447 behavior error

### ISSUE THREAD

**Issue by quick0831** [logisim-evolution/logisim-evolution#1385]
I was trying to use 7447 for my circuit, but I found that the truth table of the IC is incorrect. It act more like a 7448.

One is that the output is negated (like 7448 do).

The other is that for input value over 9, it does not produce the correct output according to the datasheet. Instead it displays A-F.

[Datasheet for 7447 & 7448](https://www.ti.com/lit/ds/symlink/sn74ls47.pdf)

**Comment by quick0831** [comment]
BTW forgot to mention, I'm using v3.7.2

**Comment by maehne** [comment]
@MarcinOrlowski: Would you maybe willing to have a look?

**Comment by quick0831** [comment]
I also used 74139 in my circuit, and I experience the same issue as stated in #1334 (kind of not important because investigated)

**Comment by quick0831** [comment]
I'm trying to look into the code

**Comment by quick0831** [comment]
Tried to build from develop branch

![螢幕擷取畫面 2022-02-03 114252](https://user-images.githubusercontent.com/44318486/152277777-19c77d97-57ce-4d4c-9a48-ded2bf7a8474.png)

**Comment by quick0831** [comment]
(the output is still inverted)

**Comment by quick0831** [comment]
I attempted to invert the output of the code, and run a small test with the datasheet

![attempt](https://user-images.githubusercontent.com/44318486/152285329-ce2c87b7-f1fa-4bde-a039-faa814fc091b.png)

**Comment by quick0831** [comment]
(the 7 segment display is set to active low)

**Comment by BFH-ktt1** [comment]
Merged, closing issue
