### ISSUE TITLE
Problem with BitSelector component

### ISSUE THREAD

**Issue by ArnaudMartinENSI** [logisim-evolution/logisim-evolution#1395]
Hello,

When i use BitSelector with the last version of logisim, theres is always an error during synthesis.
The value of nrOfInputBits haven't got the good value (always +1) in hdl file.

HAve a good day.

Thanks for your help.

**Comment by BFH-ktt1** [comment]
Fixed in my latest push, closing

**Comment by ArnaudMartinENSI** [comment]
Thank for your help.
How can i download your latest push ?

**Comment by BFH-ktt1** [comment]
You can download a nightly build version, it contains the latest PR's.

**Comment by ArnaudMartinENSI** [comment]
Thank you. I find the nightly build. I asked on other issue about screen size. I don't know if you think it's possible.
