### ISSUE TITLE
No enable with DFlipFlop

### ISSUE THREAD

**Issue by ArnaudMartinCaen** [logisim-evolution/logisim-evolution#1402]
Ii it possible to add a enable port with DFlipFlop, like logisim software.

Thank yo for your help.

**Comment by BFH-ktt1** [comment]
If you need an enable, please use the register component

**Comment by ArnaudMartinENSI** [comment]
Thank you for your help. But there is no "Set" Pin on the register component.
I need a A flp flop, with reset, set and enable.

Have a good day.

**Comment by BFH-ktt1** [comment]
You can than "just" put a mux in front of the flipflop that either keeps the current state or takes the new state.

**Comment by ArnaudMartinENSI** [comment]
Thank you for your answer and your help. I did that and it works, but my schematic is largest.

**Comment by BFH-ktt1** [comment]
Closing this issue

**Comment by maehne** [comment]
@ArnaudMartinCaen: You can put the D-FF with the Mux in front into a sub-circuit and draw a custom appearance, which resembles the D-FF and adds the requested enable pin. If you use this sub-circuit then in your circuit, it should become more compact. Does this address your need better?
