### ISSUE TITLE
Research and perhaps move main method tests to junit

### ISSUE THREAD

**Issue by davidhutchens** [logisim-evolution/logisim-evolution#1415]
The code contains 4 main methods that may be intended as tests. These should be move to junit tests as appropriate. The four main methods are:

* [src/main/java/com/cburch/hex/Test.java](https://github.com/logisim-evolution/logisim-evolution/blob/master/src/main/java/com/cburch/hex/Test.java):  public static void main(String[] args)
* [src/main/java/com/cburch/logisim/util/AlphanumComparator.java](https://github.com/logisim-evolution/logisim-evolution/blob/master/src/main/java/com/cburch/logisim/util/AlphanumComparator.java):  public static void main(String[] args)
* [src/main/java/com/cburch/logisim/gui/hex/HexFile.java](https://github.com/logisim-evolution/logisim-evolution/blob/master/src/main/java/com/cburch/logisim/gui/hex/HexFile.java):  public static void main(String[] args)
* [src/main/java/com/cburch/logisim/analyze/gui/Analyzer.java](https://github.com/logisim-evolution/logisim-evolution/blob/master/src/main/java/com/cburch/logisim/analyze/gui/Analyzer.java):  public static void main(String[] args)

**Comment by maehne** [comment]
@davidhutchens: Can this be closed since PRs #1438 and #1446 got merged in the meantime?

**Comment by davidhutchens** [comment]
@maehne: PRs #1438 and #1446 moved the main test method from HexFile to junit. There are three other main methods listed in this issue that should be examined. So I will leave this issue open pending a resolution for those.

**Comment by davidhutchens** [comment]
With the merge of #1955, all the main test drivers have been converted to JUnit.
