### ISSUE TITLE
Bug in Combinational Analysis simplification function

### ISSUE THREAD

**Issue by BlackGoku36** [logisim-evolution/logisim-evolution#1420]
To minimize: `(x+y) (~x+z) (y+z)`
-> `(y+x) (y+z) (~x+z)                   [Re-arrange]`
-> `(y+xz) (~x+z)                           [(A + B) (A + C) = A + BC]`
-> `~xy + yz + x~xz + xzz`
->` ~xy + yz + xz`

We get: `~xy + yz + xz`
But the circuit made by combinational analysis gives: `xy + yz + ~xz`

<img width="763" alt="Screenshot 2022-03-24 at 9 53 29 PM" src="https://user-images.githubusercontent.com/36535717/159963263-e199277f-c5e8-43f9-a279-5944a1195bd9.png">
Edit: Last two circuit text is flipped, second is by hand, third is by simplification function

Tested on:
- MacOS Monterey 12.1
- Logis Evolution v3.7.2

Hope these are enough info

**Comment by BFH-ktt1** [comment]
Sorry, I cannot reproduce this bug, and furthermore the simplification of this circuit is: $$\overline{x}\cdot y + x cdot z$$. could you provide the .circ file that generates this bug and a description how you come to the result (the steps).

**Comment by BFH-ktt1** [comment]
If you use the maxterms you get:
![Screenshot from 2022-03-24 18-04-34](https://user-images.githubusercontent.com/13875618/159971180-b0e7010f-6bf8-4a8d-ad63-18ddbc6ef352.png)
Hence in both cases correct....

**Comment by BFH-ktt1** [comment]
All the screen-shots you show above show the correct behavior of the analyzer, in the first screen it implements the circuit you typed in as expression, and in the second and third window it creates the minimal form using the sum-of-product or the product-of-sum form. So where you think that there is a bug?

**Comment by BlackGoku36** [comment]
Oh, I thought it simplifies by itself when you generate from typed expression, I got bit confused there. Thank you for your time.
