### ISSUE TITLE
Feature request: change name of selected tunnels

### ISSUE THREAD

**Issue by prlaba** [logisim-evolution/logisim-evolution#1432]
Currently, if I want to change the names of multiple same-named tunnels in a circuit, I have to change them individually.

That's because, if I select the same-named tunnels and enter a new name, name is applied to the first tunnel, but name_1, name_2, etc. is applied to the others, leaving them all disconnected.

For example, if I select three tunnels named A, and I change the name of the first tunnel to B, the first tunnel is renamed B but the other two tunnels are renamed B_1 and B_2.  As a result the three tunnels are no longer connected.

This requires me to change the names of same-named multiple tunnels individually, leading to circuit errors if I neglect to change the name of any of the same-named tunnels.

I'm not sure of the reasoning behind the "name_n" naming feature, as it seems to have little or no benefit and likely causes problems (previously same-named tunnels become disconnected).

My preference would be to eliminate the "name_n" naming scheme and instead assign any new name to *all* selected tunnels.

If you have to maintain the current tunnel naming scheme for backward compatibility, consider adding a new application option, "Assign same name to all selected tunnels".

**Comment by BFH-ktt1** [comment]
Closing as #1527 got merged, please reopen if problem persists.
