### ISSUE TITLE
Combinational analysis with more than 8 bit of inputs

### ISSUE THREAD

**Issue by maehne** [logisim-evolution/logisim-evolution#1436]
Logisim-evolution claims to be able to synthesise truth tables with up to 20 bit of inputs. However, the application seems to freeze when copy & pasting 512 random 0/1 entries from an Excel/Libreoffice sheet (see attached ODS file) into a truth table with 9 bit of inputs and 1 bit output. For an 8 bit input table, it works, but Logisim-evolution nevertheless freezes for quite some time before becoming reactive again. So, maybe the simplification algorithm is just running and not yet finished, but any feedback about it is lacking from the Logisim-evolution side (besides the noise of the fan). I did my test with Logisim-evolution 3.8.0dev (commit 35ebc2df) on macOS High Sierra 10.13.6.

[random01s.ods.zip](https://github.com/logisim-evolution/logisim-evolution/files/8473591/random01s.ods.zip)

**Comment by BFH-ktt1** [comment]
Has been fixed by the merged PR, closing
