### ISSUE TITLE
Function not well minimized

### ISSUE THREAD

**Issue by JesusSalido** [logisim-evolution/logisim-evolution#1445]
I get a not well minimized function. Check the next K-map:
![2022-04-19_225426](https://user-images.githubusercontent.com/1169697/164094008-b3102b07-7456-4e59-8998-4fc183e11f8f.png)

The same in the classic Logisim:
![2022-04-19_225712](https://user-images.githubusercontent.com/1169697/164094395-2d8b28ad-5454-4c08-84e8-79a6a27d822d.png)

Thx.

**Comment by R3dst0ne** [comment]
There are situations where you don't want the redundant terms to be removed.
It might be a good idea to make the removal optional with a checkbox.

**Comment by BFH-ktt1** [comment]
Closing, as PR gas been merged. Please reopen if problem persists.
