### ISSUE TITLE
Define Logisim-evolution version number in a single file

### ISSUE THREAD

**Issue by alexandremalki** [logisim-evolution/logisim-evolution#147]
After introducing 5cca9c57 by @maehne the version number has to be modified each time in the file src/com/cburch/logisim/Main.java and the file Info.plist.

Please find a solution to unify that. So there is only one file to change. 

Thank you.

**Comment by MarcinOrlowski** [comment]
@maehne Can you please change subject of this ticket to be more self explanatory please?

**Comment by maehne** [comment]
@MarcinOrlowski: Done.

We still have two places to edit for updating the Logisim-evolution version number:

* `gradle.properties`
* `src/main/java/com/cburch/logisim/Main.java`

**Comment by MarcinOrlowski** [comment]
I think we should generate java file with version number from Gradle so any version bump would be in one place. Will take a look.

**Comment by MarcinOrlowski** [comment]
Closing as this is already addressed by #885

* #885
