### ISSUE TITLE
TTL 74266 incorrectly drives its outputs HIGH

### ISSUE THREAD

**Issue by btb** [logisim-evolution/logisim-evolution#1470]
Real 74x266 ICs have open-collector outputs, which means they aren't capable of driving their outputs high. This lets you connect the outputs directly together with other OC outputs without causing conflicts, and you need a pull-up resistor to bring the level high.

As implemented in logisim-evolution, however, the 74266 does drive its outputs high, so connecting more than one together will cause errors.

PR #1468 is for fixing this

**Comment by BFH-ktt1** [comment]
Is merged, closing :-)
