### ISSUE TITLE
FPGA Commander: Dialogue to assign individual signals to a DIP switch or LED matrix is not resisable

### ISSUE THREAD

**Issue by maehne** [logisim-evolution/logisim-evolution#1480]
The FPGA Commander dialogue to assign individual signals to a DIP switch or LED matrix is not resizable:

![grafik](https://user-images.githubusercontent.com/1174243/179394356-00a82d3a-63a9-422c-a9fc-e3be95c6a4bd.png)

**Comment by BFH-ktt1** [comment]
Closing, please reopen if problem persists
