### ISSUE TITLE
Wiki documentation enhancement

### ISSUE THREAD

**Issue by alexandremalki** [logisim-evolution/logisim-evolution#151]
Hi all,
It would be nice to go through all the issue that were not bugs, but considered like it because of the lake of documentation Logisim is suffering from. This way a documentation could be written to avoid issues from being posted again and again for similar matters that are only a normal Logisim behaviour.

Thank you

**Comment by MarcinOrlowski** [comment]
Closing this one. This is very generic request. Sure docs could be (always) improved but that's hard to achieve with limited manpower We currently have [Discussions](https://github.com/logisim-evolution/logisim-evolution/discussions) for all the subjects not being explicit bug/feature requests. PRs improving manuals are always welcome though.
