### ISSUE TITLE
Crash when loading certain files

### ISSUE THREAD

**Issue by codeBodger** [logisim-evolution/logisim-evolution#1516]
When I attempt to load [this file](https://github.com/logisim-evolution/logisim-evolution/files/9351393/My_Computer_New_Custom_RAM.circ.zip) (zipped to allow upload), Logisim crashes and reports:
```
java.lang.OutOfMemoryError: Java heap space
```
If the rest of the stack trace would be helpful, I can post it later, but since there's no log, I can't copy and paste.  

I'm running Zorin OS 15 Lite (Based on Ubuntu), if that might help.  I haven't been able to test this on any other systems.

**Comment by BFH-ktt1** [comment]
I can reproduce the issue, thanks for the report!
