### ISSUE TITLE
Hovering over inputs doesn't show label

### ISSUE THREAD

**Issue by XEN486** [logisim-evolution/logisim-evolution#1517]
no idea if this is where I should put this but hovering over inputs of anything doesn't show its little label (hovering over the clock input, doesn't show that its supposed to be a clock etc)

**Comment by R3dst0ne** [comment]
Is `Show components tips` (`File>>Preferences>>Layout`) activated?

**Comment by maehne** [comment]
Closing due to missing feedback to the proposed solution. @XEN486: Feel free to reopen if it didn't work and the problem persists.
