### ISSUE TITLE
UI Fonts look ugly

### ISSUE THREAD

**Issue by SashaPGT** [logisim-evolution/logisim-evolution#1522]
Looks like the UI fonts in Logisim-evolution is not antialiased, which makes it look ugly with jagged edges compared to the original Logisim. Anyone else facing this issue?

![Screenshot from 2022-08-23 09-54-56](https://user-images.githubusercontent.com/64822291/186059979-43576f22-c5d9-48e1-8190-d56a370c05b8.png)

**Comment by maehne** [comment]
Please, check whether the option "Use anti aliasing" is set to on in tab "Layout" of the Window -> Preferences dialogue:

![grafik](https://user-images.githubusercontent.com/1174243/186210768-f8368fb0-3033-497d-8130-9c2019565671.png)

If the option is on and antialiasing is not working, please provide more details, about which exact version/package you are using and on what platform (processor, Linux distribution, X Windows or Wayland?, JDK version).

**Comment by SashaPGT** [comment]
![image](https://user-images.githubusercontent.com/64822291/186212837-08875899-391d-4c1e-9502-c2a0b9fe2939.png)

The antialiasing option is already on. Happens to both my laptop (Intel GPU) and desktop (NVIDIA GPU, with proprietary driver 515). I'm using the Flatpak version of Logisim Evolution 3.7.2 on Fedora Workstation (GNOME) 36 on an amd64.

Happens on both X11 and Wayland. The host JDK is openjdk 11.0.16 2022-07-19 (shouldn't matter? since Logisim Evolution is installed via Flatpak)

**Comment by BFH-ktt1** [comment]
This could be a flatpack issue, please try to install logisim "native" and see if you have the same problem.

**Comment by SashaPGT** [comment]
I tried installing the .jar version and the UI fonts rendered fine, so this is definitely a Flatpak issue.

Also, I tried messing around Flatpak settings (via Flatseal) and found out that after enabling `share=ipc` the UI fonts now render correctly.

**Comment by BFH-ktt1** [comment]
I'll try to find out how we can fix this in flatpak, however, with very low priority as I, for the moment, try get as much bugs/issues fixed as possible for the next release, which we plan real soon. Can you live for the moment with the current solution?
Thanks again for the issue and your effort to pin-point the problem!

**Comment by SashaPGT** [comment]
I'll try to get that into the [manifest](https://github.com/flathub/com.github.reds.LogisimEvolution/blob/master/com.github.reds.LogisimEvolution.yml)

**Comment by SashaPGT** [comment]
flathub/com.github.reds.LogisimEvolution#23
