### ISSUE TITLE
Wrong tunnel label on clock input causes synthesis to hang in DRC phase

### ISSUE THREAD

**Issue by maehne** [logisim-evolution/logisim-evolution#1523]
The following circuit (also attached as [tunnel_bug.zip](https://github.com/logisim-evolution/logisim-evolution/files/9405542/tunnel_bug.zip) to this message) with a wrong tunnel label on the clock input of the last D-flip-flop will cause the FPGA Commander to hang in the "Performing Design Rule Check (DRC) phase":

![grafik](https://user-images.githubusercontent.com/1174243/186216606-891411ba-9276-431e-92e5-c3458d7b2e45.png)

Closing the FPGA Commander window won't help. The circuit file needs to be closed first, before it becomes operational again.

**Comment by BFH-ktt1** [comment]
Closing as PR#1526 got merged, please reopen if problem persists.
