### ISSUE TITLE
Missing UI display strings when saving a RAM image over an existing file

### ISSUE THREAD

**Issue by kjcolley7** [logisim-evolution/logisim-evolution#1533]
When right clicking a RAM component and selecting the "Save image..." context menu entry, if you choose a file that already exists, an alert box will pop up asking if you're sure you want to overwrite the file. Except, it says something like "overwriteConfirmationMessage" rather than a user-presentable display string like "Are you sure you want to overwrite this file?".

Using Logisim Evolution 3.7.2 (from brew) on macOS 12.3.1.

**Comment by BFH-ktt1** [comment]
This is the same problem as reported in #1514, closing this one, as it will get fixed when #1514 gets fixed
