### ISSUE TITLE
Color mapping for K-maps starts with Map color #2 rather than #1

### ISSUE THREAD

**Issue by JesusSalido** [logisim-evolution/logisim-evolution#1558]
This is a little annoying bug that I discovered after trying to recover the legacy colors of Logisim K-maps in Logisim-EVO changing color preferences. After color check in simulation preference window, I realized that K-maps start with Map color 2 rather than number 1 (this one is really omitted).

![2022-10-07_123847](https://user-images.githubusercontent.com/1169697/194535043-c4503fd2-8b3d-4d4e-93aa-472c50d613e3.png)
![2022-10-07_123836](https://user-images.githubusercontent.com/1169697/194535057-d562721a-28ad-4ca4-b052-940b29d86390.png)

**Comment by BFH-ktt1** [comment]
Has been fixed by my latest PR. Closing, please reopen if the problem persists.
