### ISSUE TITLE
Chinese is not properly written in language list

### ISSUE THREAD

**Issue by smallg0at** [logisim-evolution/logisim-evolution#1566]
The proper name for Chinese is "中文", but in preferences it is always shown as "cn".

The root cause may be the wrong use of this language code.

Chinese (Simplified) should be "chs" (language code) instead of "cn" (country code).

Not sure about this, should check the docs I guess.

**Comment by smallg0at** [comment]
No longer needed, fixing this in pull request

**Comment by R3dst0ne** [comment]
Please do not close issues until the PR that fixes them got merged.

**Comment by smallg0at** [comment]
Fixed in #1565.
