### ISSUE TITLE
Hardcoded Attribute table background color

### ISSUE THREAD

**Issue by RakibRyan** [logisim-evolution/logisim-evolution#1576]
Can't figure out how do I change this part to dark mode.
![Screenshot (7)](https://user-images.githubusercontent.com/85598032/199709532-5e417f8f-7944-4098-bc9a-70a8c703a6d1.png)

**Comment by MarcinOrlowski** [comment]
This component's background color currently hardcoded so theme change won't affect it as of 3.8

**Comment by maehne** [comment]
Thanks @MarcinOrlowski for picking up the issue!

**Comment by BFH-ktt1** [comment]
I'm closing this issue as #1578 has been merged. Please reopen if the problem persists.
