### ISSUE TITLE
West and east are inverted in the french documentation

### ISSUE THREAD

**Issue by lapingenieur** [logisim-evolution/logisim-evolution#1579]
West and East are inverted on this picture:

![image](https://raw.githubusercontent.com/logisim-evolution/logisim-evolution/master/src/main/resources/doc/fr/img-guide/tutorial-shot-labeled.png)

It is found in `src/main/resources/doc/fr/img-guide/tutorial-shot-labeled.png`

**Comment by maehne** [comment]
@lapingenieur: Thanks, for pointing us to this documentation issue!

@mbaillif: Would you maybe willing to fix it?

**Comment by mbaillif** [comment]
Ok, I'm looking at this.

**Comment by maehne** [comment]
Closing as PR #1585 got merged.
