### ISSUE TITLE
Make releases include native Arm builds for Mac M1 & M2

### ISSUE THREAD

**Issue by davidhutchens** [logisim-evolution/logisim-evolution#1584]
@ridicolos asks in #499 when we will build natively for the M1. It is time to make that happen.

Github doesn't currently seem to have an Arm based Mac we can run nightly builds on. It might be possible to target some non-github machine, but I keep hoping they will make one available eventually.

So for now, I suggest we try to build the latest release for M1/M2. Would @BFH-ktt1 be willing to give it a try on his M1 Mac Mini? The next paragraph describes how to set it up so you can continue to build the intel version and still build the arm version on the same machine.

All that should be required is to download the arm AArch64 version of the jdk for the Mac [here](https://jdk.java.net/19/), strip the download attribute before unzipping it (xattr -c openjdk-19.0.1_macos-aarch64_bin.tar.gz), unzip it, and change the JAVA_HOME shell environment variable to point to it. Then clean and build the createDmg target. I'm not sure how it will name the dmg. It might be necessary to rename it to include -arm64 to make the name different from the x86_64 version.

I have some ideas about modifying build.gradle.kts so it keeps better track of the architecture and it wouldn't be necessary to clean between builds. The way it currently works, it might build the previous architecture if you fail to clean.

@ridicolos should be able to build his own app that way too, of course. If you have already installed the arm version of the jdk, you can skip most of that and just download and build the project with ./gradlew createApp. Then look in build/dist.

**Comment by ridicolos** [comment]
This seems to work fine. I compiled it on my m1 Mac without any problem:

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/25656713/201106695-fd8e3841-6ea6-40cb-9fba-85ca91d56855.png">

**Comment by ridicolos** [comment]
@davidhutchens: I ran `./gradlew createDmg` and got the file with the following name: `logisim-evolution/build/dist/logisim-evolution-3.8.0.dmg`

**Comment by davidhutchens** [comment]
Thank you! That tells me how I need to change our build code to make it fairly easy to make both architectures for our releases.

**Comment by ridicolos** [comment]
Is there not a solution to make the DMG mutli-binary? If I am not mistaken this is the common way in which these are mostly released.

**Comment by davidhutchens** [comment]
The problem is that there is no universal binary Java JDK. The build process includes the Java runtime in the app. You must build a version with a JDK matching the version that it builds. That is why we cannot build the Arm version on a machine that is x86_64. But we can build both versions on a machine that is Arm because Arm systems run x86_64 binaries.

**Comment by davidhutchens** [comment]
Completed with #1588.

**Comment by ridicolos** [comment]
Will we see the native build in the next release and when will this approx. be?

**Comment by davidhutchens** [comment]
@ridicolos: Yes, the native arm64 build for macOS should be available in the next release. I'm not sure when that will be, however. Unfortunately, github does not provide arm64 hardware to allow us to build it in our nightly builds.

**Comment by ridicolos** [comment]
@davidhutchens Some time has passed now. Any idea when the next release will be available?

**Comment by davidhutchens** [comment]
@ridicolos: I am not sure when the next release will happen. Perhaps @BFH-ktt1 or @maehne can provide some insight.

**Comment by maehne** [comment]
From our side, there’s not much pressure for a new release, so that we would normally target the next one for September/October, when we‘ll use Logisim-evolution in the next round of our digital design classes. However, if the community is interested in a new release, as there have been quite some fixes since 3.8.0, we could IMHO consider to release 3.9.0 with only those issues assigned to its milestone, which are pressing/easy to resolve. Help in resolving or reprioritising these issues is welcome. Currently, our time at disposal for Logisim-evolution is limited. In the end, it depends primarily on @BFH-ktt1 to drive the release.
