### ISSUE TITLE
Windows package not included in Nightly

### ISSUE THREAD

**Issue by davidhutchens** [logisim-evolution/logisim-evolution#1589]
The Windows .msi package was not included in the nightly after #1588 was merged.

Perhaps I didn't guess the osArch string correctly and the package name isn't what I expected.

@BFH-ktt1: Would you please post the precise package file names that are generated by the current develop branch for the four combinations (macOS, Windows) x (Intel, Arm) so I can fix the nightly and the README?

**Comment by BFH-ktt1** [comment]
@davidhutchens : I hope to take some time this weekend to look into it, sorry, I have been quite busy lately :-)

**Comment by maehne** [comment]
@BFH-ktt1: Ping

**Comment by davidhutchens** [comment]
@BFH-ktt1: Could you please provide the filenames I requested previously so this issue can be resolved?

**Comment by BFH-ktt1** [comment]
@davidhutchens : Windows intel: logisim-evolution-3.9.0-amd64.msi

**Comment by davidhutchens** [comment]
@BFH-ktt1: Thank you!

**Comment by davidhutchens** [comment]
Closing as completed with #1645.
