### ISSUE TITLE
A vulnerability in logisim 3.8.0

### ISSUE THREAD

**Issue by maybezEasonZhao** [logisim-evolution/logisim-evolution#1621]
![image](https://user-images.githubusercontent.com/121920649/210551557-631d3ece-27a9-485a-82f9-f9b3cb1c5102.png)
![image](https://user-images.githubusercontent.com/121920649/210551889-ac024f05-f6e3-42bc-a8f3-645954bf2b0e.png)
[bug.txt](https://github.com/logisim-evolution/logisim-evolution/files/10343890/bug.txt)

**Comment by maehne** [comment]
@maybezEasonZhao: I cannot reproduce the issue you show in your screenshots with your submitted bug circuit in Logisim-evolution 3.8.0. I will therefore close this issue. Feel free to reopen if you have more detailed steps allowing us to reproduce the issue.
