### ISSUE TITLE
Bad Buzzer

### ISSUE THREAD

**Issue by 18001767679** [logisim-evolution/logisim-evolution#1627]
Why don't you have a speaker that does like a real speaker(changes amplitude not frequency)
Or a frequency speaker that can do an inverse cosine/fourier transform
Because of thin transmission lines?
We don't want to have to make an array of speakers(the sounds add up but we still dont want to make that much speakers)
Also do you have speakers that support floats?(integers are awsome and f->i is awsome too,but we need more precision)

Just learned that the correct term is buzzer. It buzzes!

**Comment by maehne** [comment]
The buzzer from the input/output library was merged from the [Logisim-Ita fork](https://github.com/Logisim-Ita/Logisim) as is. I guess the buzzer's interface was designed in that way to simplify its implementation and also its use to, e.g., signal something or play simple tunes using a ROM. It also ensures consistent audible sound even if the simulation speed is changed in Logisim-evolution. You might have noticed that the simulation speed depends not only on the settings in the menu, but also the complexity of the circuit as well as how much needs to be redrawn in the visible canvas. Logisim's notion of time is very limited. Therefore, I don't see an obvious way how to implement your wished behaviour in a usable and reliable way independent of the simulated clock frequency to get audible output.

We are not using it actively in our projects that we do with the students. So this is not of high priority to us. PRs implementing a more realistic speaker/buzzer are welcome.

@zdimension might be able to comment on this issue more, as he has used it himself.

For the moment, I close this as not planned, but feel free to reopen to discuss the issue further or provide a PR for review.
