### ISSUE TITLE
Imported Logisim 2.7.1 and pressed Ctrl+S (overwritten)

### ISSUE THREAD

**Issue by ogamespec** [logisim-evolution/logisim-evolution#1630]
1. Import some_old.circ from Logisim 2.7.1
2. Press Ctrl+S in Evo

3:

![image](https://user-images.githubusercontent.com/5828819/211196532-b71b1123-ffa3-435a-9c2a-7224735fd685.png)

**Comment by maehne** [comment]
Please, be more specific what is not working and provide a file to reproduce your issue. We don't have the ressources to guarantee compatibilit with classic Logisim. Though, we are open for PRs fixing such issues. For the moment, I will close this issue. Feel free to reopen and provide the details to reproduce your issue.

PS: Please, be a bit more careful in your choice of words. Someone might get offended by such images / language.
