### ISSUE TITLE
PLA does not respond to blue input

### ISSUE THREAD

**Issue by 18001767679** [logisim-evolution/logisim-evolution#1636]
I wanted to use one as a blue(hiz) detector but failed.
Now I have to use a bit extender and a FPNEG's error bit

**Comment by maehne** [comment]
Using a PLA or FPNEG to detect high-Z at an input is misusing these two components. The only option I see would be using a pull up and a pull down together with pass gates to connect them one afte another to the input line and see if the line stays either pulled up or pulled down or has the opposite value. If it has the opposite value, you can be sure the input is driven. I'll close this issue as invalid. Feel free to reopen if you think you have additional arguments worth a discussion.
