### ISSUE TITLE
 (bug)N-Type Transistors don't work!

### ISSUE THREAD

**Issue by timofeevAS** [logisim-evolution/logisim-evolution#1670]
I have started use Logisim Evo. And after i tried to made Logic AND (with N-Type transistors) and also Repeater and Inverter. Transistors dont work. (But P-type good work)
![image](https://user-images.githubusercontent.com/90041514/218981374-069ec58c-e3e3-4311-9822-733b32187a77.png)

**Comment by R3dst0ne** [comment]
They work as intended.
Take a look at:
#1386
#1295
#431
