### ISSUE TITLE
There is a problem with the transistor.

### ISSUE THREAD

**Issue by maybezEasonZhao** [logisim-evolution/logisim-evolution#1674]
The simulation results of the same circuit in v3.8.0 and v2.7.1 are different, which may be due to the transistor problem.
![image](https://user-images.githubusercontent.com/121920649/220317785-40f0345a-c9a0-496d-b1d9-0e46ff4c7990.png)

**Comment by BFH-ktt1** [comment]
Closing this issue as resolved
