### ISSUE TITLE
Documentation hardly/not readable with dark themes

### ISSUE THREAD

**Issue by R3dst0ne** [logisim-evolution/logisim-evolution#1675]
I noticed that the documentation is hardly readable, with some darker themes.

Here is how it should look like (`FlatLaf IntelliJ`):
![Javahelp-FlatLaf_IntelliJ](https://user-images.githubusercontent.com/62245695/220393624-ffac2e41-1b55-4b28-96c9-6b0147ec746e.png)

`FlatLaf Dark` is hard to read:
![Javahelp-FlatLaf_Dark](https://user-images.githubusercontent.com/62245695/220393950-a6bb9cc7-fb26-4306-ac64-25f1e54b70bf.png)
And `GTK+` is impossible to read.
![Javahelp-gtk](https://user-images.githubusercontent.com/62245695/220394165-81c3a5d0-064a-4042-84b7-40c65e1b9226.png)

**Comment by PhilipWaldman** [comment]
Is this issue still open? And if it is still open can I be assigned to it?

**Comment by maehne** [comment]
Closing as PR #1986 got merged. Feel free to reopen if issue persists in other places.
