### ISSUE TITLE
Adding TTL 7487

### ISSUE THREAD

**Issue by aplq** [logisim-evolution/logisim-evolution#1682]
Short description: 4-bit True/complement, zero/one 
This would be a good 74 series chip for use behind an adder to set up for add/subtract and +1/-1 operations
Link to datasheet: [https://archive.org/details/bitsavers_tidataBookVol2_45945352/page/n403/mode/2up](https://archive.org/details/bitsavers_tidataBookVol2_45945352/page/n403/mode/2up)

I currently intend to add this myself, as it seems like an easy first part.

**Comment by maehne** [comment]
@BunchOfBits has contributed over the past months a lot of TTL components to Logisim-evolution. You may review his [merged PRs](https://github.com/logisim-evolution/logisim-evolution/pulls?q=is%3Apr+is%3Aclosed) to get an idea what is need. He may be able to answer if questions should arise.

**Comment by BunchOfBits** [comment]
Do you want me to add this one ? It shouldn't be much work, it is a very simple circuit

**Comment by aplq** [comment]
Just created a pull request: Adding TTL 7487 #1684

**Comment by BunchOfBits** [comment]
My question just got answered ;-)
