### ISSUE TITLE
Spelling error in canvas documentation

### ISSUE THREAD

**Issue by weszhuang** [logisim-evolution/logisim-evolution#1687]
![image](https://user-images.githubusercontent.com/10148048/225508401-7a3bb60b-3fbf-42c6-b985-5730cb7416b6.png)
Shift-Mouse wheel is misspelled as Schift-Mouse wheel

**Comment by EmergencyTemporalShift** [comment]
If this is already merged, shouldn't it be closed?

**Comment by maehne** [comment]
@EmergencyTemporalShift: Yes, thanks!
