### ISSUE TITLE
Nightly build is not triggered Nightly 

### ISSUE THREAD

**Issue by R3dst0ne** [logisim-evolution/logisim-evolution#1714]
While looking at the [nightly builds](https://github.com/logisim-evolution/logisim-evolution/actions/workflows/nightly.yml), I noticed that there is a build for each commit.
Is this wanted behavior?
What is the status on this one?
https://github.com/logisim-evolution/logisim-evolution/blob/a8e3c096bbdad57975bbe4e8731c1e6cf5d09023/.github/workflows/nightly.yml#L13-L26

**Comment by davidhutchens** [comment]
The problem, as I understand it, is that scheduled workflows only work on the default branch. We cannot easily schedule a nightly build that runs each night on the develop branch. Therefore, this issue is related to #1552. See my suggestion there.

**Comment by davidhutchens** [comment]
Since we now have main as the default branch Nightly is running at midnight. PR #1796 adjusts it to only run at midnight and not run after each closed PR.
