### ISSUE TITLE
Rename circuit after creation

### ISSUE THREAD

**Issue by cybercoder-naj** [logisim-evolution/logisim-evolution#1715]
In the Menu, there is no way to rename a circuit once it has been created. There should be a menu option to rename the circuit in the menu

**Comment by davidhutchens** [comment]
If you select the circuit by double-clicking on it in the Design panel and look at the Properties below, you will see that the Circuit Name is a property. And you may change it there.

**Comment by maehne** [comment]
I agree with @davidhutchens that this functionality is already present though in a different convenient place. Therefore, I am closing this issue as resolved. @cybercoder-naj: Feel free to reopen if you have additional arguments/need for discussion.
