### ISSUE TITLE
Feature Request: Export image: add PDF and EPS format

### ISSUE THREAD

**Issue by 45gfg9** [logisim-evolution/logisim-evolution#1724]
<img width="416" alt="截屏2023-04-11 15 09 25" src="https://user-images.githubusercontent.com/37043529/231083266-3618ff26-418b-491e-84a3-eb5005bed740.png">

Add an option to export as PDF and EPS here

**Comment by BFH-ktt1** [comment]
Dear @45gfg9 : Thank you very much for your request. Unfortunately we are quite limited in resources for the moment, such that I do not think that we will tackle this feature in the near future. Any PR's in this direction are of course welcome.

**Comment by 45gfg9** [comment]
Looking back in 16 months, I think this can be closed since it already supports Ti*k*Z output, and can be used to generate PDF / EPS format. Some tweaks to the generated code are needed (colors, fonts, etc.) but it will do.
