### ISSUE TITLE
Analog Voltage input library addition

### ISSUE THREAD

**Issue by charlieaustin37** [logisim-evolution/logisim-evolution#1755]
This is my first issue/feature request, so apologies in advance if this is in the wrong format, or if I am posting this in the wrong place.  Any feedback is greatly appreciated!

I want to use an analog voltage input to digital output conversion, but I couldn't find any built-in components or libraries to accomplish this function.  Specifically, I want to have 4 different levels of digital output states based on the value of the analog input.  A user would also obviously need the ability configure which voltage level gives what value of output, etc.

Perhaps this is too high-level of a function to be added as a default component, but it is a very common function in a wide variety of disciplines, and so I think it would be an extremely useful feature.  I am going to work on implementing this function with the components already available to me in Logisim, and I will publish the library here if I am successful.

Thanks,
Chuck

**Comment by maehne** [comment]
This feature request is a duplicate of issue #1750. I suggest continuing the discussion there.
