### ISSUE TITLE
Add support for 7-segment scanning arrays

### ISSUE THREAD

**Issue by BFH-ktt1** [logisim-evolution/logisim-evolution#1764]
Many FPGA-boards have arrays of 7-segment displays, where the segments are connected together, and the display is selected by either a display enable pin (common anode or common cathode pin) like in the Alchitry (thanks @chuckb for the great video), or a decoder like on the GECKO5Education. By adding this IO-component, logisim can map a/multiple standard 7-segment display on one or multiple displays.

**Comment by BFH-ktt1** [comment]
Closing this issue as #1786 got merged

**Comment by JayTaq** [comment]
How to use this 7-segment scanning arrays in Logisim Evolution schematic?

**Comment by maehne** [comment]
You don't use 7-segment scanning arrays directly in the schematic. Instead, you just use normal 7-segment displays (or even LEDs). The scanning array logic is added in the background by the FPGA Commander while net listing your design.  The properties of a scanning 7-segment array have to be defined only once in the FPGA board editor for each board featuring such displays. You can, e.g., open the built-in board `ALCHITRY_AU_IO` in FPGA > FPGA Board Editor and then double click on the upper left big rectangle to open the properties of the scanning array of that board:

<img width="808" height="566" alt="Image" src="https://github.com/user-attachments/assets/7cf37262-44e2-495c-a8db-66cb341eaf85" />

<img width="576" height="842" alt="Image" src="https://github.com/user-attachments/assets/42117907-471b-49f4-9677-c668de20a5a5" />
