### ISSUE TITLE
Strange method in ReaderInputStream

### ISSUE THREAD

**Issue by davidhutchens** [logisim-evolution/logisim-evolution#1770]
I looked at some of the output from CodeQL in #1768. The first file I happened to look at was `.../file/ReaderInputStream.java` where the following method is declared:

[public synchronized int read() throws IOException](https://github.com/logisim-evolution/logisim-evolution/blob/65aadc532751c8c759b091eeb915853bec642158/src/main/java/com/cburch/logisim/file/ReaderInputStream.java#L104C3-L131C1)

The body of the method:

    if (in == null) throw new IOException("Stream Closed");
    byte result;
    if (slack != null && begin < slack.length) {
      result = slack[begin];
      if (++begin == slack.length) {
        slack = null;
      }
    } else {
      final var buf = new byte[1];
      result = (read(buf, 0, 1) <= 0) ? -1 : buf[0];
    }

    if (result < -1) {
      result += 256;
    }

    return result;
  

It complains about `result += 256` having a narrowing conversion. Indeed, 256 is an integer and result is declared to be a byte. But I had trouble with the purpose of the line, especially since it is clearly a no-op because the low-order 8 bits of 256 are zero.

Then I realized that if result were to be declared as int, the addition would actually remove all the sign-extension from the byte (the if applying that for all negative values except -1). So I thought the fix would be to change the declaration of result to int.

But that doesn't entirely fix things. If the byte that was read is all one bits (i.e. 255), the method would return -1, which presumably means end-of-file.

It seems to me that the logic of this method needs to be adjusted to return the unsigned character value from the input or a -1 if no more characters remain.

The current version returns the signed character value (by sign extension in the return statement) and -1 for either end-of-file or 255 in the input.

Thoughts?

**Comment by MarcinOrlowski** [comment]
Yep, this looks like "smart code" that misses the 255 case completely. Looks like just a bug for me.
