### ISSUE TITLE
Small problem in the appearance of classic-Logisim RAMs

### ISSUE THREAD

**Issue by mbaillif** [logisim-evolution/logisim-evolution#1772]
![image](https://github.com/logisim-evolution/logisim-evolution/assets/42096681/83366dbe-f1cd-4dfe-8338-7e0a76d1533a)

For example, for a 64x16 ram with the "Line size" property on Octo

**Comment by mbaillif** [comment]
I launch a PR that corrects this point

**Comment by maehne** [comment]
Closing as fixed by PR #1838. Thanks @mbaillif!
