### ISSUE TITLE
Suggestion: Please reduce size and change color of POR component

### ISSUE THREAD

**Issue by prlaba** [logisim-evolution/logisim-evolution#1808]
Please consider reducing the size and change the color of the POR component.  The large orange rectangle is out of character with all of the other components.  It looks cartoonish and takes up too much space in a circuit.

A small white square with a single output and "POR" in its center would be more in tune with the style of other components.

**Comment by mbaillif** [comment]
I launch a PR to adapt this component

**Comment by davidhutchens** [comment]
This issue should be fixed in the main branch with #1843.

@prlaba: would you please check that and either let us know what else should be done or close this issue as completed.

**Comment by prlaba** [comment]
I’d be happy to verify, but don’t know how to build/download/install on Windows from main branch .  Instructions somewhere?

Thanks.

**Comment by maehne** [comment]
> I’d be happy to verify, but don’t know how to build/download/install on Windows from main branch .  Instructions somewhere? Thanks.

You can check out our [nightly builds](https://github.com/logisim-evolution/logisim-evolution#nightly-builds).

**Comment by mbaillif** [comment]
I also have a little help here for a Windows installation.
https://www.baillifard.com/logisim/en/html/guide/install/index.html

it's still only a draft

**Comment by maehne** [comment]
Closing as fixed by PR #1843, which is part of Logisim-evolution 3.9.0.
