### ISSUE TITLE
Version 3.8.0 Release Chinese Translation Mistake

### ISSUE THREAD

**Issue by ilovecopy** [logisim-evolution/logisim-evolution#1810]
<img width="302" alt="image" src="https://github.com/logisim-evolution/logisim-evolution/assets/58297115/4529a0d3-b4a2-4d2d-bceb-b71c8434f5c1">

In the Properties of the Text,the Horizontal Alignment，'Right' should be translated to “右边” in Chinese version other than "正确的”。

**Comment by BFH-ktt1** [comment]
@ilovecopy : Could you please check in the main branch if the problem still persists (see the nightly build). There has been a good effort on the Chinese translation lately.

**Comment by ilovecopy** [comment]
thanks,the problem is solved in the recent version
