### ISSUE TITLE
Need a Bidirectional Pin component

### ISSUE THREAD

**Issue by prlaba** [logisim-evolution/logisim-evolution#1812]
It's painful to create a bidirectional bus in L-E because all pins are either input pins or output pins.  You're forced to "split" a bidirectional bus into a "Bus In" input pin and "Bus Out" output pin.

A new _Bidirectional Pin_ component would solve that.

Here's how that component might work:

The pin can be connected to a wire or the output of a bidirectional component, like RAM (when configured with bidirectional data pins).

When the pin is connected to a wire or component whose value is Z, the pin behaves as an input pin-the user can enter value for the pin that is passed through to the wire or component.

When the pin is connected to a wire or component whose value is _not_ Z, the pin behaves as an output pin.  The pin's value is the same as the wire or component.

In the case of a multi-bit bidirectional pin, the pin behaves as an input pin if _all_ of the wire or component's bits are Z; otherwise it behaves as an output pin (its value may include Z bits).

Errors are propagated through the pin in both directions.

To illustrate, consider a circuit containing a RAM component configured with bidirectional data pins.  The circuit contains a single Bidirectional Pin component.

When the RAM's (active-high) OE pin is low, its data pins are Z.  In that case the bidirectional pin acts as an input pin. When the RAM's OE pin is high, its data pins are not high-Z, so the bidirectional pin acts as an input pin.

With this new Pin type, the existing _Output Pin?_ attribute would need to be changed to _Pin Type_, with a drop-down box listing the three types (Input, Output and Bidirectional).

To the best of my knowledge L-E's RAM component is the only one with bidirectional pins.  If L-E supported a Bidirectional Pin component, other circuits could then be created to emulate other real-life components with bidirectional pins, like dual-ported RAM, bus transceivers, etc.

Comments?

**Comment by BFH-ktt1** [comment]
@prlaba : Thank you for your feature request. The request for bi-directional pins has been raised several times. Unfortunately the simulation engine of logisim does not support bidirectional pins on sheet level. To implement these types of pins would require a complete rewrite of the core of logisim. The only bi-directional pins that logisim can offer are on top-level with the `Port I/O` component.
Closing this issue as won't implement as this would require a complete redesign of logisim, sorry.
