### ISSUE TITLE
Does it support download into ALTERA MAX10?

### ISSUE THREAD

**Issue by top58525785** [logisim-evolution/logisim-evolution#1850]
Hello
everybody
Does logsim support download into MAX10？I add FPGA model is 10M08SCM153

when i download program into fpga, It shows error as below:

Info: Command: quartus_map logisimTopLevelShell --optimize=area
Error (125095): Part name 10M08SC153 is invalid
Info (125063): set_global_assignment -name DEVICE 10M08SC153
Error (281000): Part name 10M08SC153 is illegal

So how to add a FPGA BOARD  and then can download? THanks

**Comment by maehne** [comment]
Yes, MAX10 is supported. However, you need to use the [full part name](https://www.mouser.ch/datasheet/2/612/m10_overview-2401081.pdf), as when you select it in Quartus Prime, when creating your HDL project targeting the board there. There seems to be one letter and one digit missing to describe your board's FPGA fully for the mapping step.

**Comment by top58525785** [comment]
Thanks for your reply
Could you help for an example for missing part
Thanks again



发自我的iPhone


------------------ Original ------------------
From: Torsten Maehne ***@***.***&gt;
Date: Sat,Sep 9,2023 1:22 AM
To: logisim-evolution/logisim-evolution ***@***.***&gt;
Cc: top58525785 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [logisim-evolution/logisim-evolution] Does it support downloadinto ALTERA MAX10? (Issue #1850)





 
Yes, MAX10 is supported. However, you need to use the full part name, as when you select it in Quartus Prime, when creating your HDL project targeting the board there. There seems to be one letter and one digit missing to describe your board's FPGA fully for the mapping step.

**Comment by maehne** [comment]
Quartus Prime offers two variants of the MAX 10 10M08SCM153 part:

* 10M08SCM153C8G
* 10M08SCM153I7G

You have to check your dev board or its schematics to know which is the one, you need to choose.

**Comment by maehne** [comment]
Closing as answered due to no further activity. Feel free to reopen in case of follow up questions to this topic.
