### ISSUE TITLE
Rendering issue with anti-aliasing on Linux

### ISSUE THREAD

**Issue by flyme2bluemoon** [logisim-evolution/logisim-evolution#1865]
## Description
It seems that anti-aliasing is causing a rendering issue on Linux.

When using anti-aliasing (turned on by default), the rendering looks like this:
<img width="1512" alt="Logisim with anti aliasing" src="https://github.com/logisim-evolution/logisim-evolution/assets/37197710/e64717a7-7ac0-48b7-8700-99187c8f28c0">

After turning off anti-aliasing, the rendering is fixed:
<img width="1512" alt="Logisim without anti aliasing" src="https://github.com/logisim-evolution/logisim-evolution/assets/37197710/45cde301-44ca-4469-ae6a-d02cd7aa2a53">

So, it seems that this rendering issue is caused by the anti-aliasing option.

The only setting I have changed from the default is the anti-aliasing option.

## System info:
OS: Fedora Linux 38 (Thirty Eight) aarch64
Kernel: 6.4.14-200.fc38.aarch64
Display server: XWayland
Compositor: Mutter 44.4-1

**Comment by R3dst0ne** [comment]
The current head of the main branch works for me without a problem (both with antialiasing enabled and disabled).

**My system**:
OS: Fedora Linux 38 (Sway) x86_64
Kernel: 6.4.12-200.fc38.x86_64
WM: Sway (Wayland) 1.8.1
Display server for LSe: XWayland
