### ISSUE TITLE
Combinational Analysis Not Fully Minimizing

### ISSUE THREAD

**Issue by UsrRed7** [logisim-evolution/logisim-evolution#1889]
Working with a 4 bit input, some desired outputs aren't fully minimized.

### Some examples:
1) Data: [1, 0, 1, 1, 0, 1, 1, 0 , 1, 1, 0, 1, 1, 1, 1, 0]
Formula: bc'd+a'b'd'+a'b'c+a'cd'+b'c'd'+ab'd+ac'+bcd'
The K-map generated:
<img width="125" alt="image" src="https://github.com/logisim-evolution/logisim-evolution/assets/91998671/a025fcd5-e340-427b-827d-5f29627b80dc">

2) Data: [0011111011110111]
Formula: b'c+ab'+a'bc'+a'bd'+bc'd+cd'+ad
The K-map generated:
<img width="119" alt="image" src="https://github.com/logisim-evolution/logisim-evolution/assets/91998671/2c4f5b91-af67-4a10-b6be-4ddb48b47173">

---
I haven't looked at the code at all, but if pointed in the right direction I may be able to help track down the reason for this issue.

**Comment by maehne** [comment]
Thanks for reporting the issue. Indeed, the form is not minimal, but at least correct. We highly appreciate any help to improve the optimization algorithm. The relevant code lives in `src/main/java/com/cburch/logisim/analyze/`. PRs are always welcome!

**Comment by superenginegit** [comment]
If no one is working on it, I would like to work on it.

**Comment by maehne** [comment]
@superenginegit: Thanks for volunteering! No one is currently working on this issue and the related issue #1914 (which I am at the moment not able to reproduce). Feel free to open a PR as soon as you would like feedback from us. You can mark it as draft als long it is not ready for merging. For the moment, I will assign you the issue.

**Comment by davidhutchens** [comment]
@UsrRed7: Could you try the latest [Nightly build](https://github.com/logisim-evolution/logisim-evolution/actions/runs/9104282361) to see if this issue was fixed?

**Comment by UsrRed7** [comment]
Sorry for the delay, but I tried it out for a bit and I also wasn't able to find any more logical issues. Thanks @superenginegit for the fix!
