### ISSUE TITLE
Multiplier not producing Unsigned numbers.

### ISSUE THREAD

**Issue by karkaratz** [logisim-evolution/logisim-evolution#1896]
Hello,

I'm trying to build a simple offset calculator using a multiplier and a subtractor (all 7 bits).
I set the multiplied as Numeric Type = Unsigned, but what is sent on the wire gets interpreted as a 2's complement.

The multiplication I'm trying to perform is 14x5 (70 in decimal, 1000110 using 7 bits).
It is interpreted as -58.

To make it work I had to extend the bits from 7 to 8.
Now, I'm not sure it is an issue of the multiplier or of the Adders/Subtractors (for which I cannot specify any "Unsigned behavior").

In the attached picture you can find the set up for the issue.

<img width="1089" alt="Screenshot 2023-10-22 alle 18 58 08" src="https://github.com/logisim-evolution/logisim-evolution/assets/18531108/e641da86-88a5-4518-84ba-123637bc353e">

**Comment by maehne** [comment]
Your circuit works as expected if you convert the binary representation to unsigned. You can confirm this by using the Probe component from the Wiring library, which allows to specify the representation to display:

![grafik](https://github.com/logisim-evolution/logisim-evolution/assets/1174243/2fe2f42d-309c-4f2b-8b5a-cf27bdfe9673)

The Hand tool displays two's complement. I am closing this issue as invalid. Feel free to reopen if questions remain.
