### ISSUE TITLE
No parallel to serial shift register in memory section

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [logisim-evolution/logisim-evolution#1910]
There are two in the ttl section, but they are not adjustable like the serial to parallel shift register in the memory section.

**Comment by maehne** [comment]
I think that the functionality requested by you is already covered in a more general way by the already existing "Shift Register" component. You just need to load the parallel value before shifting it out. It's also easy to create custom shift registers of any variety using a register, two or more splitters and some Muxes (for implementing the control signals and their priority wrt. each other). In any case, a finite state machine or counter is required to control the parallel to serial conversion. I will close this issue as answered. Feel free to reopen if you think functionality is missing.
