### ISSUE TITLE
Difference between LSe and Holycross designs for certain components is unclear

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [logisim-evolution/logisim-evolution#1911]
Could there be some hover text or something over the drop-down entries to say the difference? Is it a simulation difference?

**Comment by maehne** [comment]
The choosable appearance of sub-circuits is purely of cosmetic nature. There should be no observable behavioural differences. I will close this issue as answered. Feel free to reopen if you think this should be still addressed in the implementation (or documentation).
