### ISSUE TITLE
The equivalent circuit does not work.

### ISSUE THREAD

**Issue by RedErr404** [logisim-evolution/logisim-evolution#1916]
I was assembling the circuit and discovered that one node was not working correctly.  The figure shows a test site for reproducing the bug.  When moving from number 3 to number 4, the trigger is reset.  In the first case, the circuit works correctly, but in others it does not.  I tested the work in other simulators, there is no similar effect.![9MQoECB7irA.jpg](https://github.com/logisim-evolution/logisim-evolution/assets/9397465/b9596a16-7975-4cd4-a3ac-d1650d4a8772)

Assembled circuit in another simulator.![7DYRUtVF1R8.jpg](https://github.com/logisim-evolution/logisim-evolution/assets/9397465/11e3c7e1-b0cc-4db2-a73e-4799f4f42b02)

Program version 3.8.0

**Comment by davidhutchens** [comment]
I may be missing something, but it looks to me that you have a race condition with which changes arrive first. In going from 3 to 4, if the first two bits drop before the third bit rises, that may cause the output from the AND to rise giving the OR a short pulse of a 1 causing its output to rise which will trigger a reset. That reset is immediate.

This is why it is recommended that you always clock the memories to ensure all inputs have settled before storing a value. A reset should not be used for logic.

**Comment by maehne** [comment]
I agree with @davidhutchens: Your design doesn't follow recommended design approaches for sequential circuits, as you misuse the asynchronous set/reset inputs of the D-flip-flops for other purposes than the power on reset. Flip-flops should be always clocked by the same clock signal and their next state should be determined via the D input to guarantee synchronous behaviour. I will close this issue as invalid. Feel free to reopen if you disagree.

**Comment by RedErr404** [comment]
What is the fundamental difference between these schemes?
![1](https://github.com/logisim-evolution/logisim-evolution/assets/9397465/48f2b58d-048b-4d2a-baa6-955c61adbfcd)
![2](https://github.com/logisim-evolution/logisim-evolution/assets/9397465/74f9d4ff-381f-4a92-afdc-7ca0b6cbdcc8)
This is the equivalent circuit. Or does this take into account delays between blocks?
![3](https://github.com/logisim-evolution/logisim-evolution/assets/9397465/bc43f04e-14c3-4fa7-b186-4f57c22278d6)

**Comment by maehne** [comment]
Please check the "Value propagation" chapter in the "Guide to Being a Logisim User" (reachable via Help -> User's Guide) for some explanations of Logisim's simulation algorithm. Indeed, gate delays are considered to some extend - though Logisim's concept of simulation time is limited. Therefore, hazards may occur due to the propagation of signal changes through the different paths from inputs to outputs traversing the different layers of gates.
