### ISSUE TITLE
No amd64.msi package

### ISSUE THREAD

**Issue by psen1** [logisim-evolution/logisim-evolution#1922]
The download instructions say "logisim-evolution-<version>-amd64.msi: Installer package for Microsoft Windows for Intel processors" but there is no *amd64.mis package.

**Comment by davidhutchens** [comment]
The amd64.msi package is the name used in our Nightly builds, and will be used in the 3.9.0 release.

In the 3.8.0 release, the name is logisim-evolution-3.8.0-x86.msi. That is actually the 64 bit build. Sorry for the confusion.

**Comment by maehne** [comment]
Closing this as it is resolved with the nightly builds and the next release.
