### ISSUE TITLE
Weird font size of the menu items and the entities

### ISSUE THREAD

**Issue by gtxzsxxk** [logisim-evolution/logisim-evolution#1934]
Hello, long time no see, when playing with the `latest nightly build` I find this issue: the font size is very weird.

This is the version built in 2023-08-02

<img width="734" alt="image" src="https://github.com/logisim-evolution/logisim-evolution/assets/73378532/a0bf172b-5ced-4f0b-b050-ff8d09ff930c">

This is what looks like now:

<img width="726" alt="image" src="https://github.com/logisim-evolution/logisim-evolution/assets/73378532/35948d38-4289-4373-b2f3-3746e685b4c0">

The one with the problem was built on 2023-12-20T00:06:44+0000. I downloaded it here: https://github.com/logisim-evolution/logisim-evolution/actions/runs/7269030544,

Do you have the same problem? If this is really a problem, I mean, not only happens on me, I'd love to find out and help solve this.

**Comment by davidhutchens** [comment]
I do not see this problem. Is it possible that you have changed a system font size? I'm not sure, without digging through the code, how we select the font size.

**Comment by gtxzsxxk** [comment]
> I do not see this problem. Is it possible that you have changed a system font size?

I ran the two versions on the same windows 11 environment at the same time. I haven't change the system font size. So I tend to believe the problem should be attributed to the commits after 2023-08-02.

> I'm not sure, without digging through the code, how we select the font size.

OK. I would have a try.

**Comment by gtxzsxxk** [comment]
This font-size problem only happened on me when I install the logisim-evolution through the windows installer provided by the latest nightly build. If I exec `java -jar logisim-evolution-3.9.0dev-all.jar`, which is downloaded from the nightly build as well, the abnormal problem goes away.

**Comment by maehne** [comment]
@gtxzsxxk: Could you please try with the [latest nightly builds](https://github.com/logisim-evolution/logisim-evolution/actions/runs/8993940035) compiled with JDK 21?

**Comment by maehne** [comment]
This may be a duplicate of issue #1452.

**Comment by gtxzsxxk** [comment]
@maehne Hi, I tested the latest nighly build and it looks pretty good. This problem might have been fixed.

![image](https://github.com/logisim-evolution/logisim-evolution/assets/73378532/7b3fa0d1-1fba-4403-8b1a-3f9d98504c20)

**Comment by maehne** [comment]
@gtxzsxxk: Thanks for testing! So this issue seems to be resolved. I am closing this issue. Feel free to reopen in case of a regression (or check whether issue #1452 is a better fit to continue the discussion).
