### ISSUE TITLE
Circuit show unexpected error as a value

### ISSUE THREAD

**Issue by LaXis315** [logisim-evolution/logisim-evolution#1952]
Hi, I was trying to use this programme to study some logic circuits and while testing the multi-value input feature I encountered this problem:
when you have both bits congruent then nothing happens, otherwise an error is sent. There doesn't seem to be any overlapping of wires in the circuit, so I can't figure out what could be causing the error

![Screenshot (223)](https://github.com/logisim-evolution/logisim-evolution/assets/10734937/dd094fa4-e924-4792-b9aa-89c287701d38)

**Comment by davidhutchens** [comment]
Did you try resetting the circuit? Does it have the problem if saved and loaded? Could you try it in the latest version of LE, 3.8.0?

To say much more, I think we need to examine the circuit.

If the problem remains in a saved and loaded .circ file, could you zip the file and drag it into a comment here?

**Comment by LaXis315** [comment]
I will carry out the required tests, but first I have to replicate the circuit as the created save file was empty. In fact, I wanted to point out this problem of the saves not seeming to work (I had made 2 for safety's sake and both were empty; there were also empty .bak files)

**Comment by LaXis315** [comment]
ok, after remaking the entire circuit the error is gone. Also the savefile now work fine

**Comment by davidhutchens** [comment]
I will close this issue as completed.
