### ISSUE TITLE
UI issues and crashes on window moving

### ISSUE THREAD

**Issue by marwinhormiz** [logisim-evolution/logisim-evolution#1956]
Hi.

I recently installed logisim evolution and quickly got issues with the UI where the UI will start to mess up completely and things start to disappear. The other issue is where the program instantly crashes whenever I try to move the window. It first started with the latest version 3.8.0, then I downgraded to 3.7.2 to check if it had anything to do with the latest release, and I was still getting the same issues. I ran the program with a debugger aswell to trigger the crash whenever I just move the windows handle and to provide a backtrace for the whole callstack.

Images:

UI:
![Skärmbild 2024-01-29 194632](https://github.com/logisim-evolution/logisim-evolution/assets/56167333/7902309d-fa7f-4588-8e43-63d9241f9a70)
![Skärmbild 2024-01-29 194639](https://github.com/logisim-evolution/logisim-evolution/assets/56167333/2693efac-f564-4f8f-bdb0-16f80d9dbdc6)

Window move crash:
![Skärmbild 2024-01-29 194218](https://github.com/logisim-evolution/logisim-evolution/assets/56167333/1ff5234f-cac1-4b9c-8076-887c57a6c93c)
![Skärmbild 2024-01-29 194233](https://github.com/logisim-evolution/logisim-evolution/assets/56167333/fb7f3b4d-a651-4346-a839-a613450928f4)

Graphics acceleration in experimental is set to "Use Defaults", but have been tried with Direct 3D aswell, still same issues.

Specs:
OS: Windows 11 Pro (10.0.22631)
CPU: Ryzen 5 5600x
Graphics card: 4060 Ti
RAM: 32GB
Java version: 8u401

**Comment by maehne** [comment]
Your JDK 8 is too old! Logisim-evolution 3.8 requires at least JDK 16. You did not indicate which pre-compiled package you used or wherever you built Logisim-evolution yourself. I would recommend you to use the provided OS-specific native installers/packages. They include already a matching Java runtime environment. You can also use one of the recent nightly builds, which fix quite some issues of version 3.8. Please report back whether this fixes your issues.

**Comment by marwinhormiz** [comment]
Oh I'm sorry, maybe I should have been more specific. I have JDK 21 according to my installed programs, but the runtime environment is 8u401, which is the latest I can find in java's official website. I don't really use Java required applications that much so hopefully I'm not confusing you with this information. I installed x86.msi and also the .jar file. When I run the executable, logisim-evolution.exe I get these issues, but if I run the .jar file immediately then everything works fine. 

![Skärmbild 2024-01-29 220706](https://github.com/logisim-evolution/logisim-evolution/assets/56167333/43719f02-c7f2-4acc-a1d9-cf90ad2f5da3)

**Comment by marwinhormiz** [comment]
Never mind the above, I just realized I don't need the Java 8 so I uninstalled it completely. But I still have the same issues only if I run the executable but not with the jar file.
