### ISSUE TITLE
wont save circuit after cancel

### ISSUE THREAD

**Issue by telephone001** [logisim-evolution/logisim-evolution#1974]
installed with logisim 3.8.0 x86 msi 
processor Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   2.11 GHz

When I open the save menu, go to recently opened and press cancel, I can't save the circuit again and I have to make it again.

**Comment by davidhutchens** [comment]
I tried to reproduce this on my Mac. I was not able to do so. I wasn't sure what "go to recently opened" means. I navigated to a place with .circ files, but that didn't trigger the problem. Neither did actually opening a recently opened .circ. Could @telephone001 provide more detailed instructions to reproduce the problem? Or someone running Windows should have a look.

**Comment by telephone001** [comment]
@davidhutchens 
1. open logisim and create a new project
2. at the top left, click file
3. then click save
4. for me a window that looks like this opens up.
when the save menu opens, there might be a tab called recently opened.
<img width="485" alt="image" src="https://github.com/logisim-evolution/logisim-evolution/assets/100259136/c69f5ea2-371a-4818-93fe-24fe18889604">
5.click X or close that window.
6. try to save again
for me it won't open up that save window again

**Comment by telephone001** [comment]
oh wait sorry it was actually called recent items.

**Comment by davidhutchens** [comment]
@telephone001: Thank you for providing more information. I tried what you suggested and the save window continues to work correctly for me. I cannot replicate the problem on the Mac.

Someone with access to Windows should try replicate it.
