### ISSUE TITLE
How do I download the latest changes?

### ISSUE THREAD

**Issue by SLicudis** [logisim-evolution/logisim-evolution#2028]
I've got the "newest version" of L.E. (3.8.0)
I was looking for the 74181 in the TTLs folder but I couldn't find it. The most recent changelog says that 74181 was added:
![image](https://github.com/logisim-evolution/logisim-evolution/assets/140275002/dc5e74ba-860e-4cf7-a847-5a04657de42a)
Could you please help me to get the newest version of logisim?

**Comment by SLicudis** [comment]
(Btw, I'm on windows 11 x86-64)

**Comment by davidhutchens** [comment]
The latest build is at [https://github.com/logisim-evolution/logisim-evolution/actions/workflows/nightly.yml](https://github.com/logisim-evolution/logisim-evolution/actions/workflows/nightly.yml). To find an actual build, you need to look down the list to find one that took a several minutes to run. If it took less than a minute, there were no changes that day and the build was skipped.

For example, right now, you can get a recent nightly build at build number 1175. For x86-64 Windows, look for the amd64.msi installer.

**Comment by davidhutchens** [comment]
I am closing this as answered.
