### ISSUE TITLE
Circute's appeareance is ignored

### ISSUE THREAD

**Issue by CheeseTastisch** [logisim-evolution/logisim-evolution#2096]
When i try to create a circute and change it's appeareance the appeareance gets saved but isn't displayed when using the circute.

My circute layout:
![grafik](https://github.com/user-attachments/assets/e08fc0af-5653-477a-9f1e-e07b2f7dbfce)

My circute appeareance:
![grafik](https://github.com/user-attachments/assets/75eaa0e4-07f2-499a-b057-c4bcb4808160)

When using the circute:
![grafik](https://github.com/user-attachments/assets/7746983c-b6c5-4ff8-b205-9370c2c7fe6c)

My circ file:
[help.zip](https://github.com/user-attachments/files/17749701/help.zip)

_Additional question_: Is there some possibility to group circutes into folders or something like that?

**Comment by davidhutchens** [comment]
The appearance issue is similar to #2052. You need to select the subcircuit and change the Appearance attribute to Custom to get the Custom appearance to show in main.

As for the grouping of circuits, there is no folder grouping option. However, I have placed a collection of circuits in a .circ file and loaded that file into another .circ file. The collection of circuits shows up in a single group associated with the loaded .circ file. This may provide what you want. As a bonus, you can load that collection into different .circ files and reuse them there. I have done this with computer components such as an ALU, Register file, etc. and then used them in different CPU designs. I hope this helps.
