### ISSUE TITLE
Logisim ITA component Programmable Generator: I cannot enter zero value as initial data

### ISSUE THREAD

**Issue by maehne** [logisim-evolution/logisim-evolution#277]
> When I try to send a low signal as the first signal of my generator, In the high signal column I place the value zero but it does not accept it and forces me to send high signals at the beginning of the transmission

This issue reported by @ArielG100 as [issue #9](https://github.com/LogisimIt/Logisim/issues/9) was reported to the [LogisimIt GitHub repository](https://github.com/LogisimIt/Logisim/) and also affects Logisim-evolution.

**Comment by BFH-ktt1** [comment]
It is even worst, the programmable generator is broken in evolution

**Comment by maehne** [comment]
This and some other Logisim ITA issues seem to have been fixed by its author in commit [c047de94](https://github.com/LogisimIt/Logisim/commit/c047de940b99a0fd8e89f9f178ace1980f8fd1a4). We should check if they apply to Logisim-evolution, too.

**Comment by maehne** [comment]
Some additional fixes in Logisim ITA were done in commit [bf526841](https://github.com/LogisimIt/Logisim/commit/bf52684130cbbbe041d6cb7d12ac8ee92cf8e082).

**Comment by maehne** [comment]
Some additional fixes in Logisim ITA were done in commit [e3500f86](https://github.com/LogisimIt/Logisim/commit/e3500f8641acfabb77b609f7fc40e418fe20b9cf).
