### ISSUE TITLE
Sequential circuits built from gates

### ISSUE THREAD

**Issue by NulAsh** [logisim-evolution/logisim-evolution#316]
Will it ever be possible to simulate such circuits?
![image](https://user-images.githubusercontent.com/32499449/71915311-1f5f3a00-3184-11ea-9235-2e72663e441e.png)

**Comment by mbaillif** [comment]
![d](https://user-images.githubusercontent.com/42096681/72010795-d2996300-3258-11ea-8eba-9327ad88248c.png)

Here is a solution for the first circuit

**Comment by h1s0k429a** [comment]
Im trying to create D / T Flip Flops but the software keeps crashing on me or gives me error.
When I try to create the flip flips in online gate simulator tools, it works. please fix this ;(

**Comment by mbaillif** [comment]
This time Loigisim is rather right.
In the help chapter "Value propagation" and "Shortcomings" the limits of logisim in this field are presented.

This circuit is particularly unstable, even in the real world. 
The one I built to see, oscillated at 16mhz with 74 series gates.

If you use this circuit it will work.
It's the same schematic, designed a little differently.

![image](https://user-images.githubusercontent.com/42096681/75098314-c709bd80-55b4-11ea-8a75-ac6424955a64.png)
