### ISSUE TITLE
obsolete command line option

### ISSUE THREAD

**Issue by mbaillif** [logisim-evolution/logisim-evolution#344]
The command line -analyze option seems to become useless.
Can't we propose the genre of -analysis off -analysis on

**Comment by maehne** [comment]
Ideally, the default setting whether the analyze feature is on or off should be configurable at build time. The comman line option should only override this default.

**Comment by mbaillif** [comment]
Okay, I keep in the documentation

**Comment by maehne** [comment]
Another option we could discuss is whether the availability of the analysis feature should be only configurable at build time. In that case the command line option and its documentation could be completely removed.

**Comment by MarcinOrlowski** [comment]
Closing as `-analyze` is now removed.
