### ISSUE TITLE
Improve German translation of FPGA Commander messages

### ISSUE THREAD

**Issue by maehne** [logisim-evolution/logisim-evolution#382]
Thanks for internationalising the FPGA Commander GUI! The German translation requires work, as some automatically translated messages have turned out to be either non-sensically or funny. Examples from `src/main/resources/resources/logisim/de/fpga.properties`:

- [x] "Sie haben ein Blatt in Ihrem Design mit einem leeren Namen gefunden. Dies ist nicht erlaubt, bitte geben Sie einen Namen an!"
- [x] "Ich habe eine bewachte Uhr gefunden. Vorsicht, die echte Hardware funktioniert möglicherweise nicht richtig!"
- [x] "Einen Verteiler gefunden, der keine Signale vom Bus zum Lüfter transportiert."
- [x] "Ich habe eine Spüle ohne Quelle gefunden!"
- [x] "Blinkende Bitdatei"
- [x] "Während des Blinkbetriebs ist ein Fehler aufgetreten."
- [x] "Fehler beim Blinken der Bitdatei."
- [x] "Ich habe %d angebrachte Boards gefunden. Wählen Sie aus, welche programmiert werden soll....."
- [x] "Platzierung und Fräsung Design"

**Comment by BFH-ktt1** [comment]
This is true for most languages except for the English version. From now on I will refrain from using Deepl for translation as it is probably less annoying to have some English text as some funny no sense making "own" language text.

**Comment by maehne** [comment]
Well, there is still some value in having the DeepL translations as a starting point. We native speakers just need to find and take the time to review those translations and improve them. That's why I created this issue.

We may discuss whether it is better to simply put the English phrases as placeholders into the translation files for the other languages. For users this might be more convenient, but less motivating for potential contributors of good translations.

**Comment by maehne** [comment]
- [ ] "Altera-Synthese, P"

**Comment by BFH-ktt1** [comment]
When no translations are available yet, we should not specify any thing in the for example German files, as logisim will take in this case automatically the english version. This is the reason why I mark them by:
#==> <key>
Such that somebody working on them knows that there is not yet a translation available, and that they can find a description of the <key> in the English version to be translated

**Comment by R3dst0ne** [comment]
> Well, there is still some value in having the DeepL translations as a starting point. We native speakers just need to find and take the time to review those translations and improve them. That's why I created this issue.
>
After working on the translations for my [Pull request](https://github.com/logisim-evolution/logisim-evolution/pull/608), I can confirm this statement. It is way easier and faster to search for errors than to translate everything by your own.

**Comment by R3dst0ne** [comment]
I fixed/added a lot of translations in bd20be0786e72d29c481e5cb438f73aae70b67fe.
Did I miss something?
If not this issue can be closed.

**Comment by maehne** [comment]
Thanks for your improvements to the German localisation @R3dst0ne!
