### ISSUE TITLE
Consider integrating simplified Chinese locales recently merged into Logisim ITA

### ISSUE THREAD

**Issue by maehne** [logisim-evolution/logisim-evolution#393]
Simplified Chinese locales were added in [PR #14](https://github.com/LogisimIt/Logisim/pull/14) to [Logisim ITA](https://github.com/LogisimIt/Logisim).

**Comment by ManiaciaChao** [comment]
Well, considering the difference in the text between the two versions, I need to spend some time rechecking and updating the text to make the translation more suitable for `logisim-evolution`. 
I will make a PR as soon as possible.

**Comment by maehne** [comment]
@ManiaciaChao: Thanks for offering your help in this area. Logisim-evolution incorporates almost all improvements done by the [Logisim ITA](https://github.com/LogisimIt/Logisim) developers as well as many from the [Logisim-evolution (Holy Cross)](https://github.com/kevinawalsh/logisim-evolution) edition by Kevin A. Walsh. In addition, it contains several additional improvements especially related to downloading the design on FPGA boards and SoC design. It is a bit unfortunate that Logisim development is carried on in separate forks since Carl Burch stopped developing the original version. Nevertheless, we are very open for collaboration and external contributions.

**Comment by R3dst0ne** [comment]
@maehne @ManiaciaChao @legion-null 
Since #1282 got merged, is this issue still relevant?
