### ISSUE TITLE
Chip Select with RAM

### ISSUE THREAD

**Issue by rhodeon** [logisim-evolution/logisim-evolution#396]
The original Logisim has a chip select port which enabled or disabled the entire component, and it was level triggered. 
There doesn't seem to be an equivalent port in Evolution. Is there a way to achieve this?

**Comment by maehne** [comment]
Well, you have the dedicated `Write enable` and `Output enable` inputs. How about connecting your `Chip select` signal directly to `Output enable` and using an AND gate in front of the `Write enable` to generate from the `Chip select` and `Write` control signals the `Write enable` signal?

You are aware that you can switch the appearance of components in their property pane to get back the classic Logisim look?

**Comment by rhodeon** [comment]
> Well, you have the dedicated `Write enable` and `Output enable` inputs. How about connecting your `Chip select` signal directly to `Output enable` and using an AND gate in front of the `Write enable` to generate from the `Chip select` and `Write` control signals the `Write enable` signal?
> 
> You are aware that you can switch the appearance of components in their property pane to get back the classic Logisim look?

Yeah. That was coincidentally how I ended up mimicking the pin.
As for the classic look, switching to it just changed the interface of the RAM and didn't create a chip enable pin. I suspected this would be the case, though.

**Comment by MarcinOrlowski** [comment]
Can we please try to evaluate if we are going to add this or not?
