### ISSUE TITLE
[Suggestion]: Moving circuit from original Logisim to Logisim Evolution

### ISSUE THREAD

**Issue by GamePlayer-PL** [logisim-evolution/logisim-evolution#490]
Hello,

I have some suggestions for moving circuits/projects from the original Logisim to Logisim Evolution.
During the import, I noticed problems with selecting the theme of the objects. Exactly, Logisim Evolution when see an object with no theme then setting it to Logisim-evolution theme.

Here's a suggestion: What if Logisim Evolution sets the classic Logisim theme when importing a project from the original Logisim?

**Comment by maehne** [comment]
@GamePlayer-PL: Sorry for the late reaction. We are still catching up from the very busy winter term.

@BFH-ktt1: What do you think? It should be feasible, as the Logisim version gets recorded in the `.circ` file.
