### ISSUE TITLE
Splitter loop gives different results in simulation and on FPGA board

### ISSUE THREAD

**Issue by maehne** [logisim-evolution/logisim-evolution#526]
A student found the following problem. The below circuit (cf. also to attached circuit file) yields different behaviour in simulation and after synthesis on an FPGA board:

![grafik](https://user-images.githubusercontent.com/1174243/111629344-7b463980-87f1-11eb-87d1-ce482363faa9.png)

In simulation, both LEDs will light up if the button is pressed. On the FPGA board, `LED_Bug` won't light up.

[VerteilerBug.zip](https://github.com/reds-heig/logisim-evolution/files/6164198/VerteilerBug.zip)

**Comment by BFH-ktt1** [comment]
Fixed by my latest PR, closing
