### ISSUE TITLE
Programmable Generator has disappeared in v. 3.4.4

### ISSUE THREAD

**Issue by CuriousMarc** [logisim-evolution/logisim-evolution#551]
No more Programmable Generator in v3.4.4? Has also disappeared from standard Logisim it seems. It was broken in current release Logisim Evolution version 3.4.1 (would not work at all).

**Comment by BFH-ktt1** [comment]
I disabled it for the moment as it is badly broken, as soon as I have more time I will look into it how to fix it

**Comment by CuriousMarc** [comment]
I thought this might be the case. Thanks for your answer, and congrats on the awesome work.

Marc
