### ISSUE TITLE
Add copy of components across two files

### ISSUE THREAD

**Issue by reds-heig** [logisim-evolution/logisim-evolution#56]
Right now, the copy of components from one file to another is impossible.
It would be a nice feature to have.

**Comment by MosheBerman** [comment]
Like a shared library across launches/documents?

**Comment by reds-heig** [comment]
The problem with shared libraries is that you have to distribute them with the .circ file. It would be nice if one could just select a component and really copy it across instances -- provided that all dependencies are satisfied.

**Comment by BFH-ktt1** [comment]
See my latest push for a partial solution

**Comment by BFH-ktt1** [comment]
The current problem with logisim is that it uses it's own clipboard (hence copy and paste are not visible to the OS). Opening a new logisim window creates an independent program instance. Both logisim instances cannot "see" each other, and hence the both clipboards are not visible too them preventing from copy-paste over two logisim instances. It might be quite a challenge to provide this feature.

**Comment by MosheBerman** [comment]
What about a shared cache on-disk or our own daemon that shared components?

**Comment by rodolforg** [comment]
Is there any interest on using java/system clipboard?
I could try to implement that...

**Comment by BFH-ktt1** [comment]
Closing as retaken in #1050
