### ISSUE TITLE
make aur package for arch linux

### ISSUE THREAD

**Issue by Unknown-User2** [logisim-evolution/logisim-evolution#561]
im on arch and have fun learning how things work with this and would love if you made a aur package for arch linux

**Comment by maehne** [comment]
For reference: [Arch Linux Java package guidelines](https://wiki.archlinux.org/title/Java_package_guidelines)

**Comment by K1ngjulien** [comment]
It seems like some people have already made AUR packages for this and except for the -git version they look up to date:

https://aur.archlinux.org/packages/logisim-evolution/

https://aur.archlinux.org/packages/logisim-evolution-bin/

https://aur.archlinux.org/packages/logisim-evolution-git/

**Comment by maehne** [comment]
Thanks @K1ngjulien for these links!

@Unknown-User2: Could you give them a try and provide us with some feedback?

Based on this, we could add instructions to our [README](https://github.com/reds-heig/logisim-evolution/blob/master/README.md) to point users to these packages and give instructions on how to install them.

**Comment by Unknown-User2** [comment]
it work good you just run `logisim-evolution` in the terminal and it runs

**Comment by maehne** [comment]
Thanks for the feedback @Unknown-User2. Did you try package `logisim-evolution` or `logisim-evolution-bin`?

**Comment by MarcinOrlowski** [comment]
As mentioned, we are unable to officially support Arch for the reasons given [here](https://github.com/logisim-evolution/logisim-evolution/issues/561#issuecomment-836660305). We can add some info to our docs but it should not be outdated - the links given above point to build 3.4.5 with note "This AUR repo has switched to a build-from-source package." whatever that means really. So we need PR from someone that knows Arch. 
Closing as there's not much we can do right now. Feel free to reopen if needed.
