### ISSUE TITLE
Consider moving logisim-evolution to an organization account

### ISSUE THREAD

**Issue by zdimension** [logisim-evolution/logisim-evolution#577]
The repository is currently owned by a personal account (`reds-heig`), I think it would better reflect the "community project" aspect if it were under an organization account, like most big open-source projects.

**Comment by maehne** [comment]
I support this idea of moving the project to its own organisation account. It would also facilitate setting up a proper web site for logisim-evolution.

**Comment by BFH-ktt1** [comment]
This has taken place today. I will close the issue.
