### ISSUE TITLE
Set up a Gitter chatroom (or other platform)

### ISSUE THREAD

**Issue by zdimension** [logisim-evolution/logisim-evolution#581]
I think it could be of use to the project to provide a chatroom related to Logisim, questions and issues with it. Maybe a Gitter space or a Discord server?

**Comment by BFH-ktt1** [comment]
I'm in favor. However, I will not have any bandwidth till June/July due to a very busy teaching schedule. After this I will look into moving logisim to it's own namespace and what can be done with respect to a chatroom. Thanks for your suggestion.

**Comment by maehne** [comment]
I think [Gitter](https://gitter.im) would be a good option. I am already using it for other projects. With the [developing integration into the Matrix ecosystem](https://blog.gitter.im/2020/09/30/gitter-element-acquisition/), the service is also much more usable on mobile platforms using the Element chat client.

**Comment by zdimension** [comment]
Indeed, it would also potentially have a better integration with other GitHub features.

**Comment by maehne** [comment]
@zdimension: OK, then let's try to go with the Discussions feature, which @BFH-ktt1 already enabled. If you feel it's not sufficient and a real chat platform would be better, feel free to reopen this issue and we can discuss this topic further.
