### ISSUE TITLE
Update the "Credits" list

### ISSUE THREAD

**Issue by zdimension** [logisim-evolution/logisim-evolution#590]
Since it was last updated, there have been lots of contributions from lots of new contributors, I think the list should be updated to reflect that

**Comment by BFH-ktt1** [comment]
@zdimension , I fully agree, but for that I need the information that those contributors have to give me. I am very happy to add them to the "credits" list, or that they add themselves and do a PR.

**Comment by R3dst0ne** [comment]
Is this issue still relevant?
Since this issue got created, the most active contributes have been added.
In addition, `credits.md` features the line `If you feel that your name should be in this list, please feel free to open a ticket.`.

**Comment by maehne** [comment]
@R3dst0ne: I agree that we can close it, as the credits got updated by several PRs in the past months.
