### ISSUE TITLE
IMPORTANT: logisim-evolution has moved

### ISSUE THREAD

**Issue by BFH-ktt1** [logisim-evolution/logisim-evolution#593]
Dear all,
We have moved logisim-evolution to it's own organisation called "logisim-evolution".
please make sure that you update your upstream reposatory with:

```
git remote set-url origin "git@github.com:logisim-evolution/logisim-evolution.git"
```

We will add more features in the near future like web site, etc.

**Comment by maehne** [comment]
@BFH-ktt1: I think we can close this issue. The old URL `https://github.com/reds-heig/logisim-evolution` gets redirected to the new one.
