### ISSUE TITLE
Icons are barely visible when using dark themes

### ISSUE THREAD

**Issue by MarcinOrlowski** [logisim-evolution/logisim-evolution#641]
Icons are barely visible when using dark themes:

![icons](https://user-images.githubusercontent.com/8041294/121545318-b5972f80-ca0a-11eb-8c2a-fd47a1ecd293.png)

In general, I posted a [question on "Discussions" about revamping icons](https://github.com/logisim-evolution/logisim-evolution/discussions/640), so please feel free to share your thoughts.

**Comment by maehne** [comment]
I completely agree with your observation that this is ugly and hampers usability of Logisim-evolution when switching to an increasingly popular dark mode theme.

**Comment by R3dst0ne** [comment]
#1487 addresses this issue. It does not fix everything, but improves most icons.
