### ISSUE TITLE
Someone unfixed my bug fix #655

### ISSUE THREAD

**Issue by davidhutchens** [logisim-evolution/logisim-evolution#674]
The current version of develop has the old HexFile.java without the fix contained in PR #655.

Could you please reapply it? Or do I need to do another PR?

**Comment by MarcinOrlowski** [comment]
High chance that's because of my PR rush :/ Sorry for that. Anyway, it looks like @BFH-ktt1 reapplied your patch in #677 Could you please check?

**Comment by davidhutchens** [comment]
Well, #677 didn't quite reapply #655. I'll wait a few days for the develop base to settle down (since my PR isn't the only one that was undone according to #680) and then I'll submit a PR to clean up as needed.

**Comment by BFH-ktt1** [comment]
Can we close this issue?
