### ISSUE TITLE
Undo/Redo bug

### ISSUE THREAD

**Issue by BFH-ktt1** [logisim-evolution/logisim-evolution#72]
When using the "clipboard" (read cut/copy/paste) the undo and redo functionality are not always functioning properly (copied pasted items are missing). As this might be of minimal importance it is still in some cases annoying ;-)

**Comment by MarcinOrlowski** [comment]
Can we have more precise repro-case?

**Comment by davidhutchens** [comment]
@BFH-ktt1 : Can this issue be closed with PR #2053? I know that it fixed some copy/paste issues with redo.

**Comment by davidhutchens** [comment]
I am closing this as completed with PR #2053.
