### ISSUE TITLE
References need to be updated

### ISSUE THREAD

**Issue by R3dst0ne** [logisim-evolution/logisim-evolution#775]
I found these outdated references to Logisim-evolution.
- [ ] [sourceforge](https://sourceforge.net/projects/logisimevolution/) download old version
- [x] [Wikipedia FR](https://fr.wikipedia.org/wiki/Logisim) old version Number, reference to old GitHub URL
- [x] [Wikipedia DE](https://de.wikipedia.org/wiki/Logisim) old version Number, reference to old GitHub URL
- [x] [Wikipedia EN](https://en.wikipedia.org/wiki/List_of_free_electronics_circuit_simulators) reference to old GitHub URL

**Comment by MarcinOrlowski** [comment]
Corrected Wikipedia entries. As for SF - can **delete** it there?

**Comment by MarcinOrlowski** [comment]
Talking about Wikipedia - it might be worth considering to have dedicated page for Logisim-evolution

**Comment by R3dst0ne** [comment]
> Corrected Wikipedia entries.

You missed
![grafik](https://user-images.githubusercontent.com/62245695/124754704-d0d25d80-df2a-11eb-9136-139a385bbb90.png)
in [DE](https://de.wikipedia.org/wiki/Logisim).
Could you update "consulté le" in [FR](https://fr.wikipedia.org/wiki/Logisim) as well.

**Comment by MarcinOrlowski** [comment]
Yes I could but I think it's wrong. "Logisim" as such is dead. And it should be clear it is dead so we should not make it look otherwise (and "evolution" does not clearly indicates it's different thingie). I will create Separate entry for "Evolution"

**Comment by MarcinOrlowski** [comment]
I am surprised to see there's no English page for Logisim?!

**Comment by R3dst0ne** [comment]
I see your point, but leaving a outdated version number is no option eighter.
You could change "Aktuelle Version" to "Nachvolger Versionen". That makes clear that these are successors.

You need to update "consulté le" in [FR](https://fr.wikipedia.org/wiki/Logisim) since https://github.com/logisim-evolution/logisim-evolution didnt exist back in october 2019.

**Comment by MarcinOrlowski** [comment]
* I updated DE, but it seems it needs approval to be published now
* Updated FR, should be online now

**Comment by MarcinOrlowski** [comment]
We now need to try to have #776 completed. But I not sure I can do this alone anyway

**Comment by MarcinOrlowski** [comment]
@reds-heig It seems that SF page is maintained by you:

![s](https://user-images.githubusercontent.com/8041294/125445815-f34ff066-903d-42f2-a30e-01a0d1db5ce3.png)

Can you please remove it?

CC: @maehne @BFH-ktt1

**Comment by R3dst0ne** [comment]
With the 3.6.0 release cumming soon, we really should try to remove the outdated version from [SourceForge](https://sourceforge.net/projects/logisimevolution/).

**Comment by MarcinOrlowski** [comment]
Yes, definitely, this one needs to be gone. @TheEvilSkeleton is it something that you can take care of, please?

**Comment by TheEvilSkeleton** [comment]
@MarcinOrlowski pardon me for my lack of understanding, but what do I need to take care of?

**Comment by MarcinOrlowski** [comment]
Of having logisim-evolution project removed from SourceForge. I thought that you may have some powers there too as it's also under "redsheigvd" type of user as Flakpak was

**Comment by TheEvilSkeleton** [comment]
Ah, I'm only involved in packaging in Flatpak and nothing else.

**Comment by MarcinOrlowski** [comment]
BTW: if that would be possible, instead of removing we may want to make SF page redirect to github? This seem to be possible and the rationale is that SF page still gets a few downloads a month so why axe working lead.

**Comment by R3dst0ne** [comment]
The version number needs to be updated again in: 
- [ ] [Wikipesia FR](https://fr.wikipedia.org/wiki/Logisim)
- [ ] [Wikipesia DE](https://de.wikipedia.org/wiki/Logisim)

**Comment by maehne** [comment]
Regarding the outdated Sourceforge page. Taking it down or redirecting it to GitHub can only be done by our colleagues from HEIG-VD in Yverdon-les-Bains. Unfortunately, @reds-heig and his colleagues have been busy more with other things in recent years. @BFH-ktt1 will bring probably this issue up next time he talks to them regarding Logisim-evolution.

**Comment by maehne** [comment]
@R3dst0ne: I updated the German and French Wikipedia pages to mention Logisim-evolution 3.6.1.

**Comment by R3dst0ne** [comment]
I'm closing, this issue since #1534 features the same (and additional) goals.
