### ISSUE TITLE
"Export log" button to analyze weird problems

### ISSUE THREAD

**Issue by reds-heig** [logisim-evolution/logisim-evolution#8]
Sometimes Logisim has a weird behaviour -- signals that change value by theirself, other signals that become undefined, ...

To debug this, it would be helpful to have a written trace of what Logisim does in those moments. Given the logging system of #6, one should have a button that dumps the whole set of logs in a file, for later analysis.

**Comment by MarcinOrlowski** [comment]
@BFH-ktt1 Can we have this closed? It's 6 yo and many things changed in meantime. It's also pretty generic and as no one fixed it for the last 6yo nor no one added any additional complains, let's close it. Apparently it's not that problematic IRL :)
