### ISSUE TITLE
Copying/Pasting RAM, then moving it twice, causes it to disappear

### ISSUE THREAD

**Issue by trayres** [logisim-evolution/logisim-evolution#832]
How to reproduce:
Select RAM item
Copy/Paste (Ctrl+C, Ctrl+V on Windows)
Move copied item once. While it is still selected, move it again.
The part will disappear, but selection handles will remain in its place. 
Now, you can click into where the RAM is supposed to be and, while it is selected, move it again.
Doing this over and over can create a bunch of handles for parts that aren't there. 

![image](https://user-images.githubusercontent.com/168285/126407549-eeeb825b-af08-43e6-a439-ecef6e8c05b2.png)

**Comment by davidhutchens** [comment]
I could not duplicate this behavior on my Mac using our latest builds. Yes, I know you are using Windows. But It might help to narrow things down if you could give us the version of Logisim-evolution you are running.

**Comment by trayres** [comment]
![image](https://user-images.githubusercontent.com/168285/126429246-c20820c5-658d-4e3e-84b1-164b291405b5.png)

**Comment by jxu** [comment]
Upload a MWE if possible

**Comment by MarcinOrlowski** [comment]
> MWE

You meant [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by jxu** [comment]
many acronyms for the same thing

**Comment by MarcinOrlowski** [comment]
mind expanding your `MWE` then? :)

**Comment by trayres** [comment]
I have not been able to reproduce this effect, let alone reproduce it in a MCVE.

I'll close the issue and re-open if I can duplicate the effect reliably.
