### ISSUE TITLE
Tightening PR merge flow

### ISSUE THREAD

**Issue by MarcinOrlowski** [logisim-evolution/logisim-evolution#843]
Thanks for merging @BFH-ktt1 #823. `CODEOWNERS` seem to be now automatically assigned for code review but the repo now needs additional configuration tweaks to make sure no non-reviewed PR slip by.

So I'd like to propose additional repository configuration changes (these needs to be done twice -> for `develop` and `master` branch respectively):

1. In repository `Settings` go to `Branches` "pane, then in `Branch protection rules` and click `Add rule`.
  1. In `Branch name pattern put `develop` (then `master`).
  2. Enable (check) the following options (the same for both branches):
    * `Require pull request reviews before merging`
      * `Dismiss stale pull request approvals when new commits are pushed`
      * `Require review from Code Owners`
    * `Require conversation resolution before merging`
    * `Include administrators`

**Comment by BFH-ktt1** [comment]
I just put in those two rules. Closing the issue
