### ISSUE TITLE
Logisim does not show connector pins

### ISSUE THREAD

**Issue by carbonmetrics** [logisim-evolution/logisim-evolution#862]
[vm0007_redd.circ.zip](https://github.com/logisim-evolution/logisim-evolution/files/6959735/vm0007_redd.circ.zip)
I am trying out Logisim 3.5.0 Evolution on a Linux Mate 20.04 system (both the deb 64 version and the Java version).

The connections on the gates do not show up. 
I see on Youtube tutorials that they should be highlighted blue.
I can't connect my pins; they remain on `x1`.

![image](https://user-images.githubusercontent.com/40055991/128668262-251e400e-9933-4927-901e-6ac460d6ce9a.png)

NB - When I work backward (from AND gate to pin) I can establish a connection (wiring remains connected when moving the gate), but the pins still remain on x1.
  
How can I connect pins in Logisim evolution?

**Comment by MarcinOrlowski** [comment]
Can you please please ZIP your example `.circ` file and attach to ticket?

**Comment by carbonmetrics** [comment]
Thanks! File attached to ticket. 
The connectors show up sometimes, and then the whole program works. 
This is about 1 in 20 times when I start up the program. 
I have not been able to reproduce the behaviour.

**Comment by R3dst0ne** [comment]
It seems 
>  File > Preferences... > Layout > Printer view

is sometimes enabled.
In this case this is not an issue with the pins but with saving/loading the preferences.

**Comment by carbonmetrics** [comment]
Yes! That seems to solve the problem. I don't think I would have ever found this. Thanks!

**Comment by BFH-ktt1** [comment]
Closing the issue
