### ISSUE TITLE
RISC-V IM simulator, blt instruction bug?

### ISSUE THREAD

**Issue by Antares95** [logisim-evolution/logisim-evolution#867]
asm code:
```
_start:
        li a1, 1
        li a2, 2
        blt a1, a2, pc+0x100
        nop
```
does not jump to pc+0x100

logisim-evolution version is (commit 374a72318ecd0c16b7c077a2260753a1ffc2861c)

**Comment by MarcinOrlowski** [comment]
Are you able to test using bleeding edge code (`develop` branch)?

**Comment by Antares95** [comment]
> Are you able to test using bleeding edge code (`develop` branch)?

Yes, `develop` branch (version: commit 4a8dd3707afede432bbad9990b74e837248a5b81) seems to have same issue

**Comment by BFH-ktt1** [comment]
This is possible, the Risc-V IM simulator was never tested in all details. Please also note that interrupt handling is not yet implemented for the Risc-V IM simulator. I will look into the details

**Comment by BFH-ktt1** [comment]
Unfortanetely it was just a stupid typo in the assembler. Fixed in my latest PR. Closing
