### ISSUE TITLE
The controlled buffer two problems

### ISSUE THREAD

**Issue by mbaillif** [logisim-evolution/logisim-evolution#873]
A) It does not have an IEC shape while the icons on the right exist.

B) Its output is (in my opinion) inconsistent, when its input is high impedance and its control is 1.

![image](https://user-images.githubusercontent.com/42096681/129441834-34624d60-1e9d-4898-9d0b-30ea8bf596e7.png)

In the red square of the figure
I will make high impedance input -> output in error.

**Comment by BFH-ktt1** [comment]
To A) I reported this already in #264. the problem is backward compatibility. As the controlled buffer in ANSI is very little, it is difficult to "cram in" the IEC symbol. Hence to do a proper job we have to drop backward compatibility on these components.
To B) I agree

**Comment by mbaillif** [comment]
The #264 escaped me, 

I notice, that buffers and non have this symbol compatible in size and very similar.
Maybe a deviation from the IEC rules. I don't know.

Is it usable, acceptable ?

I imagine you have already thought of this, it's just to transcribe my thoughts. 
And there are other issues I don't know about.

**Comment by mbaillif** [comment]
it is noted, I resume in al doc as soon as possible

**Comment by BFH-ktt1** [comment]
@mbaillif : Please nite that the buffer has the same Problem B). I also corrected here the behavior. Thanks for updating the doc!

**Comment by R3dst0ne** [comment]
@BFH-ktt1 @mbaillif 
Can this issue be closed?
