### ISSUE TITLE
Display problem after Fix #867

### ISSUE THREAD

**Issue by Antares95** [logisim-evolution/logisim-evolution#897]
Display problem after Fix #867

Use Risc-V IM Simulator's assembler write assemble code:
```
_start:
        li a1, 1
        li a2, 2
        blt a1, a2, pc+0x100
        nop
```
Then click "Run the code" button, and then start the simulator.
That BLT instruction display as "blt a2, a1, pc+256"(should be "blt a1, a2, pc+256"), but the execution result is correct.

version: c4a87e12894b1d54f70a671fadd535b102078b2d

**Comment by BFH-ktt1** [comment]
Closing this issue, it should be fixed with my latest PR. Please reopen if the problem persists
