### ISSUE TITLE
LineBuffer to simplify HDL generators

### ISSUE THREAD

**Issue by MarcinOrlowski** [logisim-evolution/logisim-evolution#912]
All the HDL generators are mixture of static text and generated lines and contents. All the content is manually stuffed into `ArrayList<String>`. This all requires tons of useless code and letters to be written as `ArrayList` do not have any usable for us helper methods. Also as `ArrayList` is just a container, generating HDL code lines sometimes was a nightmarish mixture of unreadable concatenated macaroni. To make this more readable one can use `String.format()`, but that unnecessary additional
typing **per line**. So I wrapped `ArrayList` with some helper methods and is almost drop-in replacement. Current code

```java
@Override
public ArrayList<String> GetModuleFunctionality(Netlist netlist, AttributeSet attrs) {
    final var c = new ArrayList<string>();
    c.add("foo:" + bar + "-" + item + "-name");
    return c;
}
```

new approach

```java
@Override
public ArrayList<String> GetModuleFunctionality(Netlist netlist, AttributeSet attrs) {
    final var c = new LineBuffer();
    c.add("foo:%s-%s-name", bar, item);
    return c.get();
}
```

There are multiple implementations of `add()` which can i.e. accept any `Collection` or if you have just
static text with no placeholders, you can go even simpler:

```java
    c.add(
        "line1",
        "line 2",
        "line 3");
```

Unfortunately in the above case no individual placeholders are supported. If you need to have generated content
blended into, use `String.format()` or ordinary string concatenation, or use global key-value placeholders, instead of `String.format()` based. The benefit is that these placeholders are shared among all `add()` calls (unless cleared),
so repeatedly used values can be set only once, and this is using `{{key}}` format instead of more error prone `$1%s`.
For example:

```java
final var c = new LineBuffer();
c.withPairs()
    .add("foo", "FOO")
    .add("bar", "BAR");
c.add(
      "This is {{foo}} and {{bar}}",
      "And this is {{bar}}")
 .add("This is {{foo}} again");
```

I converted most of the HDL builders. I tried not to modify the code, with the following exceptions:
* I corrected indentation (i.e. `ELSE` at wrong column) in multiple HDL generators,
* I splited several HDL ternary to have `?` and `:` in separate lines **and** the `?` and `:` characters opening their lines

**Comment by BFH-ktt1** [comment]
I like the proposed changes a lot, however, I think that it requires a second run to get things completely cleaned up. I'm happy to help in this effort.
