### ISSUE TITLE
Missing packages in nightly builds

### ISSUE THREAD

**Issue by R3dst0ne** [logisim-evolution/logisim-evolution#939]
Since [Nightly #43](https://github.com/logisim-evolution/logisim-evolution/actions/runs/1161452321) the packages don't get build.
At first glance, it seems this bug could be related to #907.

@MarcinOrlowski

**Comment by MarcinOrlowski** [comment]
#941 shall fix that. PTAL

**Comment by R3dst0ne** [comment]
This problem is resolved.

I have a question regarding this topic. (I'm not really familiar with nightly builds.)
In my understanding, there is supposed to be one nightly build per day, if something changed. Why do we have multiple (e.g. seven today)?

**Comment by MarcinOrlowski** [comment]
It's because it's not set up as nightly yet. To make this happen, worker YAML file must be merged into main branch otherwise `schedule` trigger won't work. And this is our case, so for now it builds after each merge to work this around. Please see #877
