### ISSUE TITLE
IEC and ANSI mixed up in DOC

### ISSUE THREAD

**Issue by R3dst0ne** [logisim-evolution/logisim-evolution#962]
![grafik](https://user-images.githubusercontent.com/62245695/131262965-078cbd39-7281-4bd6-a8d9-fb20dbd2c5d1.png)

@mbaillif

**Comment by mbaillif** [comment]
I take note, and I correct later
Thanks

**Comment by R3dst0ne** [comment]
It got mixed up in the text under the illustration as well.
> Because the `IEC` style tends to be more popular in the U.S., while the `ANSI` style tends to be more popular in Europe, some people refer to these styles according to these regions. 

(@mbaillif you did not correct this in c5405e2)

**Comment by BFH-ktt1** [comment]
@mbaillif and @R3dst0ne :
Maybe I'm mistaking, but the "square-shaped" symbols are IEC (so to the right in the picture), and the left are ANSI-symbols.
Furthermore, IEC is used in Europe and ANSI in the rest of the world :-)

**Comment by mbaillif** [comment]
The bigger it is, the less it shows :-))

I wanted to go too fast, I'm confused.

But I won't be caught again, I'll do it at the next PR.

**Comment by BFH-ktt1** [comment]
Closing this issue as #916 has been merged
