### ISSUE TITLE
The Command-line options need some attention

### ISSUE THREAD

**Issue by R3dst0ne** [logisim-evolution/logisim-evolution#963]
The Command-line options need some attention.
-  `-analyze` 
    - [x] removed (#977)
    - [x] #344
- `-accents` does not seem to work. 
    - [x] removed (#1009)
    - [x] I propose to overhaul and rename it to `-ascii`.
- [x] `-testvector` is not mentioned by `-help` (outdated `-test` is)
- [x] `-test-circuit`, `-test-fpga-implementation`, `-test-circ-gen`, `-questa` are undocumented. (#983)
- [x] `-gates` I would prefer `ANSI` and `IEC` over `shaped` and `rectangular` for the gate style options. (1014)
- [ ] the windows executable does not support parameters.
- [x] conform to the [GNU Standards for Command Line Interfaces](https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html).

**Comment by maehne** [comment]
I basically agree. However, we should only add short forms for options, where it makes sense and does not potentially cause confusion. Short options should be single letter, so that they can be combined if sensible.

**Comment by MarcinOrlowski** [comment]
Unless you got different implementation, may I suggest the discussion to go in #981?

**Comment by maehne** [comment]
Well, I will have my comments to your PR #981, but this issue is more general about the provided command line options and their documentation. We should make sure that your PR addresses all of them.

**Comment by MarcinOrlowski** [comment]
@maehne any work pending here or we can have this ticket closed?
