### ISSUE TITLE
Add link of Discord community server

### ISSUE THREAD

**Issue by zdimension** [logisim-evolution/logisim-evolution#999]
I've created a Discord server for logisim-evolution: https://discord.gg/ggSZD6WA4z

I know GitHub already provides the Discussions system, but having a dedicated IM platform is a plus, imo.

**Comment by MarcinOrlowski** [comment]
We already [have one](https://discord.gg/4ksaEmQ3) in testing, so please join

**Comment by zdimension** [comment]
Indeed, wasn't aware of it. Joined it right now

**Comment by zdimension** [comment]
Do you mind adding me the `admin` role? I asked Redstone but he doesn't have the privileges to
